### ISSUE TITLE
Any plans toupgrade to bootstrap 5?

### ISSUE THREAD

**Issue by thecodejack** [bestguy/sveltestrap#110]
Now that bootstrap 5 is on the way https://github.com/twbs/bootstrap/projects/11

any plans to upgrade to same?

**Comment by bestguy** [comment]
Hi @thecodejack , yes although we'll probably keep master on v4 until Bootstrap 5 is out.  In meantime we can do 5.0-alpha/beta/etc versions on a v5-dev branch.

No time at the moment, but can start a branch whenever folks would like to contribute.

**Comment by thecodejack** [comment]
sure..I would love to start on same in couple of days...

**Comment by bestguy** [comment]
I'm closing in favor of #156 , and we've started a v5 branch here: https://github.com/bestguy/sveltestrap/tree/v5
