### ISSUE TITLE
Missing toast/icons

### ISSUE THREAD

**Issue by dym-sh** [bestguy/sveltestrap#116]
the https://github.com/bestguy/sveltestrap/blob/master/stories/toast/Icons.svelte
is copy-paste from Sample of the same dirrectory

i would help, but atm not sure what supposed to be there,
smth like https://bootdey.com/snippets/view/alerts-with-arrow ?

**Comment by bestguy** [comment]
Hi @dym-sh ,
Sorry for delay in reply.
Thanks for the heads up,  this has been corrected: https://sveltestrap.js.org/?path=/story/components--toast
