### ISSUE TITLE
Label has unused export property

### ISSUE THREAD

**Issue by solinad21** [bestguy/sveltestrap#119]
i am using sapper

i get this message when run as dev my saper app :

- - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - 
Label has unused export property 'xs'. If it is for external reference only, please consider using `export const xs`
18:   export { fore as for };
19:   export let id = '';
20:   export let xs = '';
                 ^
21:   export let sm = '';
22:   export let md = '';
- - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - 

how remove this message?

do you have sapper install steps?

**Comment by bestguy** [comment]
Hi @solinad21 , this is confusing warning, as these props are actually used, just indirectly:

https://github.com/bestguy/sveltestrap/blob/master/src/Label.svelte#L30

I'll see if there's some way to let sapper know this.

**Comment by bestguy** [comment]
Hi @solinad21 , this should be corrected in sveltestrap@3.3.2
