### ISSUE TITLE
How to use spacing classes

### ISSUE THREAD

**Issue by vrde** [bestguy/sveltestrap#120]
Hi, I tried to create a container with custom spacing. I noticed the `Container` component exports `className`, so I tried this:

```html
<Container className="my-2">
    smth
</Container>
```

But it doesn't work. Any idea on how I can use [spacing classes](https://getbootstrap.com/docs/4.3/utilities/spacing/)?

**Comment by bestguy** [comment]
Hi @vrde , Svelte uses `class` like normal HTML, so just:

`<Container class="my-2">`

The [export you see](https://github.com/bestguy/sveltestrap/blob/master/src/Container.svelte#L6) is just so we can reference internally in JavaScript, since class is a reserved keyword.
