### ISSUE TITLE
Modal sizes css classes

### ISSUE THREAD

**Issue by frederikhors** [bestguy/sveltestrap#121]
If you use something like PurgeCSS and Modal component the css classes are not compiled in final js bundle.

I'm talking about these: https://getbootstrap.com/docs/4.4/components/modal/#optional-sizes

```
.modal-sm
.modal-lg
.modal-xl
```

Can we add them somehow?

**Comment by bestguy** [comment]
Hi @frederikhors , haven't used PurgeCSS and typically use Bootstrap themes from CDNs, but can you explain its removal logic?  Does it inspect a compiled app?

 It seems difficult for a tool like this to know about classes like this:
https://github.com/bestguy/sveltestrap/blob/master/src/Modal.svelte#L206

Thinking you could probably hack a hidden element like this in your app like this:

`<div class="modal-sm modal-lg d-none" />`

but kind of ugly!

**Comment by frederikhors** [comment]
They are needed to be all in full length:

```
.modal-sm
.modal-lg
.modal-xl
```

**Comment by bestguy** [comment]
Closing as unrelated to Sveltestrap code, please comment if there is an idea on how the lib can help with this.

**Comment by xpuu** [comment]
You can whitelist specific classes in your [PurgCSS config](https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md).
