### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by czlinNYC** [bestguy/sveltestrap#124]
How does one style the sveltestrap components? 
I am attempting to style the drop down and yeah. No idea how to do it.

**Comment by bestguy** [comment]
Hi @czlinNYC , this library is for using Bootstrap components in Svelte, so the styling comes from Bootstrap.   We basically use bootstrap class and Bootstrap theme provides the look.  This is not a library like styled-components.

However you can customize your Bootstrap theme by overriding the classes used, dropdowns for example: https://getbootstrap.com/docs/4.4/components/dropdowns/#examples

Or you can use a different Bootstrap theme, such as from Bootswatch: https://www.bootstrapcdn.com/bootswatch/

Some examples:

Default:
<img width="179" alt="Screen Shot 2020-01-29 at 6 21 18 AM" src="https://user-images.githubusercontent.com/405608/73364619-ba1cd700-425f-11ea-801a-9e0bef0f5c02.png">

Darkly:
<img width="167" alt="Screen Shot 2020-01-29 at 6 21 28 AM" src="https://user-images.githubusercontent.com/405608/73364622-bb4e0400-425f-11ea-8acf-01376a133bfd.png">

Sketch:
<img width="176" alt="Screen Shot 2020-01-29 at 6 21 36 AM" src="https://user-images.githubusercontent.com/405608/73364629-bdb05e00-425f-11ea-9fbf-f61f8e65926e.png">

**Comment by czlinNYC** [comment]
Wow thank you for your prompt reply. I appreciate it. I am only using a few components of sveltestrap, so I think and entire theme will be overkill. I styled the components I am using with a css file loaded after the bootstrap in the <head/>. It seems to be sufficient for my project. Thank you again I will pass this to my coworkers.
