### ISSUE TITLE
Input type submit is missing

### ISSUE THREAD

**Issue by orzen** [bestguy/sveltestrap#128]
The input type submit is not listed in the if-statement that checks the type it will therefor end up render nothing.

Is there any other way to submit forms?

**Comment by bestguy** [comment]
Hi @orzen , oops!  That's a silly mistake, will fix up!

In short term` <input type="submit" class="btn btn-primary" value="Save">` etc will work

**Comment by bestguy** [comment]
Hi @orzen ,
This should be corrected with #133 , released in sveltestrap@3.3.3

Can you please confirm and update this issue?

Usage has a color prop so it uses correct Bootstrap bth styles:
`<Input type="submit" color="primary" value="Save">`
