### ISSUE TITLE
Typescript types support?

### ISSUE THREAD

**Issue by majkelbed** [bestguy/sveltestrap#129]
I would like to use this lib in my svelte + typescript(preprocess) project, yet i'm having trouble importing it due to lack of types. Can someone provide @types/sveltestrap any soon? <3

**Comment by bestguy** [comment]
Hi @majkelbed , that would be awesome, I had assumed Svelte did not work well with TS.  For example: https://github.com/sveltejs/svelte/issues/3677

What's your toolchain and how might this work?  Any example svelte libs that do support this for reference?

**Comment by mistlog** [comment]
I implemented [svelte-draft](https://github.com/mistlog/svelte-draft) so that we can use svelte with full power of typescript, however, someone doesn't like it, or even hate it due to the custom JSX syntax.

> What's your toolchain and how might this work?

Anyway, add types to sveltestrap can be achieved in this way: https://github.com/bestguy/sveltestrap/pull/132. I added a demo for using sveltestrap with these types in repo [sveltestrap-demo](https://github.com/mistlog/sveltestrap-demo).

I create a pull request so that we can see the diff clearly, feel free to close it if it's not the preferred way to add types.

**Comment by majkelbed** [comment]
I managed to pull this off with webpack as a module bundler, [ts-loader](https://github.com/TypeStrong/ts-loader) for imports, [svelte-loader](https://github.com/sveltejs/svelte-loader) for svelte imports and [svelte-preprocess](https://www.npmjs.com/package/svelte-preprocess) so i can do sth like this:
```
<script lang="typescript">
 export let buttonName:string;
 let buttonRef:HTMLElement;
</script>
<button bind:this={buttonRef}>{buttonName}</button>
```
It is not 1st class typescript support, but i like it more than svelte-draft (sorry man 😄 ).
I do not recommend awsome-typescript-loader, had isuess with it, but you can try.
**You do not get any typescript support in your templating part**, but for me it is ok.
I moved all my business logic to separate .ts files and .svelte is only ui/reactive component.

I choose webpack for two main reasons:
1. I implemented this whole structure into old project with old libraries that did not work with rollup.
2.I knew already webpack so.. 😄 

@mistlog Thanks, looks like what i need! But for sure we could provide @types so anyone can benefit from it, maybe I will try. Just started using typescript so still learning.

**Comment by bestguy** [comment]
Sorry for delay in reply, but thanks @majkelbed for starting this.  Since the interface is very similar, do you think we could fork or reuse code from [@types/reactstrap](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reactstrap/index.d.ts)?

**Comment by BlackFenix2** [comment]
@bestguy i have to ask, why do we need the dist folder? if for SSR we are encouraged to import from the /src folder why dont we just use that as the main package directory? that would allow an easier developer experience with typescript/javascript.  what is the point of outputting to umd or es if the client is going to compile the .svelte file to javascript anyway?

sorry if its a dumb question, im new to npm bundling. I can just get the d.ts files from reactstrap and copy/paste here.

**Comment by BlackFenix2** [comment]
@bestguy i tried to reuse code from  @types/reactstrap, i event tried the index.d.ts file from the PR https://github.com/bestguy/sveltestrap/pull/132. i cannot get the svelte components to play nice without red curly lines. 

## Button.d.ts
```ts
/**
 * Button
 */
export declare type ButtonColor = "primary" | "secondary" | "success" | "danger" | "warning" | "info" | "light" | "dark";
export declare type ButtonSize = "lg" | "sm";
export interface IButtonProps {
    color?: ButtonColor;
    size?: ButtonSize;
    outline?: boolean;
    disabled?: boolean;
    active?: boolean;
}
export declare function Button(props: IButtonProps): void;
```

## Implementation in svelte

```svelte
<script lang="typescript">
  import {
    Alert,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavItem,
    NavLink,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem,
    Button,
  } from 'sveltestrap';

  import Collapse from 'sveltestrap/src/Collapse.svelte';

  let isOpen = false;

  const handleUpdate = (event) => {
    isOpen = event.detail.isOpen;
  };
</script>

<style>

</style>

<div />
<Navbar color="light" light expand="md">
  <NavbarBrand href="/">svelte-showcase</NavbarBrand>
  <NavbarToggler on:click={() => (isOpen = !isOpen)} />
  <Collapse {isOpen} navbar expand="md" on:update={handleUpdate}>
    <Nav navbar>

      <NavItem>
        <NavLink href="about">About</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="blog">Blog</NavLink>
      </NavItem>
      <NavItem>
        <NavLink disabled href="#">Disabled Link</NavLink>
      </NavItem>
    </Nav>
  </Collapse>
</Navbar>

<Button >www</Button>

```

i get this error: 
![image](https://user-images.githubusercontent.com/15244006/87867519-a7a47000-c95b-11ea-8655-9fe2140e2d42.png)


im stumped-ish on what component type we are supposed to declare in *.d.ts, i tried the SvelteComponent type but it looks like it wasn't meant for JSX syntax. i just need help declaring the svelte component as a valid JSX component and i can work on getting the rest of the type definitions fixed.

**Comment by BlackFenix2** [comment]
i did find this svelte component type definition inside my local node_modules, so far no success on replicating this logic for our custom svelte components.

```d.ts
import { SvelteComponent } from './Component';
export declare function dispatch_dev<T = any>(type: string, detail?: T): void;
export declare function append_dev(target: Node, node: Node): void;
export declare function insert_dev(target: Node, node: Node, anchor?: Node): void;
export declare function detach_dev(node: Node): void;
export declare function detach_between_dev(before: Node, after: Node): void;
export declare function detach_before_dev(after: Node): void;
export declare function detach_after_dev(before: Node): void;
export declare function listen_dev(node: Node, event: string, handler: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | EventListenerOptions, has_prevent_default?: boolean, has_stop_propagation?: boolean): () => void;
export declare function attr_dev(node: Element, attribute: string, value?: string): void;
export declare function prop_dev(node: Element, property: string, value?: any): void;
export declare function dataset_dev(node: HTMLElement, property: string, value?: any): void;
export declare function set_data_dev(text: any, data: any): void;
export declare function validate_each_argument(arg: any): void;
export declare function validate_slots(name: any, slot: any, keys: any): void;
declare type Props = Record<string, any>;
export interface SvelteComponentDev {
    $set(props?: Props): void;
    $on<T = any>(event: string, callback: (event: CustomEvent<T>) => void): () => void;
    $destroy(): void;
    [accessor: string]: any;
}
export declare class SvelteComponentDev extends SvelteComponent {
    constructor(options: {
        target: Element;
        anchor?: Element;
        props?: Props;
        hydrate?: boolean;
        intro?: boolean;
        $$inline?: boolean;
    });
    $capture_state(): void;
    $inject_state(): void;
}
export declare function loop_guard(timeout: any): () => void;
export {};

```

**Comment by bestguy** [comment]
Hey @BlackFenix2 , I didn't realize svelte source is now in TS, can our types just extend SvelteComponent here?
https://github.com/sveltejs/svelte/blob/master/src/runtime/index.ts

**Comment by BlackFenix2** [comment]
@bestguy i did that and now im getting:

```error
'Button' cannot be used as a JSX component.
  Its instance type 'Button' is not a valid JSX element.
    Type 'Button' is missing the following properties from type 'ElementClass': $$prop_def, render, context, setState, and 4 more.ts(2786)
```

ill try to discord svelte and see what i could be missing. im not really sure how to tell typescript that this is not a JSX element.

**Comment by BlackFenix2** [comment]
@bestguy an update, the d.ts files work if svelte component you are calling the module from does not have the identifier:
```html
<script lang="typescript"></script>
```
if the .svelte file is using javascript the type definitions provide intellisense without issue, otherwise the typescript runtime complains that the component is not valid JSX (it is not a react component). 

i updated the (javascript) working Button.d.ts file, it works perfectly if the consumer uses javascript but it screams at consumers using typescript. once i figure out how to write this for Typescript projects ill update all the d.ts files and finalize the PR.

```ts

import {  SvelteComponentDev} from 'svelte/internal';


/**
 * Button
 */
export declare type ButtonColor = "primary" | "secondary" | "success" | "danger" | "warning" | "info" | "light" | "dark";
export declare type ButtonSize = "lg" | "sm";
export interface IButtonProps {
    color?: ButtonColor;
    size?: ButtonSize;
    outline?: boolean;
    disabled?: boolean;
    active?: boolean;
    children: any;
}




declare class Button extends SvelteComponentDev {
  constructor(
    props:IButtonProps
  )
}

export default Button



```

**Comment by BlackFenix2** [comment]
I went onto svelte discord and figured out that the SvelteComponentDev type is picking up globals causing the type checker to scream.

good news is we now have a way to add type definitions for our umd and es bundles. gonna be a big labor of love to update each component by hand.

```d.ts
import { SvelteComponentDev } from 'svelte/internal';

export declare type ButtonColor =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'light'
  | 'dark';
export declare type ButtonSize = 'lg' | 'sm';
export interface IButtonProps {
  color?: ButtonColor;
  size?: ButtonSize;
  outline?: boolean;
  disabled?: boolean;
  active?: boolean;
  children: any;
}

/**
 * Bootstrap Button
 */
declare class Button extends SvelteComponentDev {
  constructor(
    props:IButtonProps
    )

  $$prop_defs: IButtonProps;
 // i got to add these types manually to quiet the type checker!!!!
  render:undefined;
  context:undefined;
  setState:undefined;
  forceUpdate:undefined;
  props:undefined;
  state:undefined;
  refs:undefined;
}

export default Button;
```

**Comment by BlackFenix2** [comment]
once https://github.com/bestguy/sveltestrap/pull/166 completes, we can close this issue.

**Comment by a7med-mahmoud** [comment]
Svelte VSCode Extension gives me this error when using event handlers like `on:click`:
`Property '$on' does not exist on type 'NavbarToggler'.ts(2339)`

**Comment by BlackFenix2** [comment]
are you using the official svelte for vscode extension? i cannot replicate the error on my vscode project.

see if you have the vscode extension here: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by a7med-mahmoud** [comment]
That's the extension I have, It also gives me errors on the `expand` property because it's declared as a boolean but it should take a string of 'sm', 'md' or 'lg'.

**Comment by a7med-mahmoud** [comment]
I'm using Sveltestrap in a Svelte & TS project acually..
using the new `node scripts/setupTypescript.js` command.

**Comment by a7med-mahmoud** [comment]
I created a `sveltestrap.d.ts` file that has this content
```typescript
declare module 'sveltestrap/@types/shared.d.ts' {
  export class LocalSvelteComponent {
    $on<T = any>(event: string, callback: (event: CustomEvent<T>) => void): () => void;
  }
}
```
then the `on:event` is fixed, but I'm still getting an error with the `expand="lg"` in the `<Collapse />`

**Comment by BlackFenix2** [comment]
@a7med-mahmoud do you have a github repo i could look at? i cannot replicate the issue with the on:event directive, i do get the similar type error on expand="lg".

**Comment by a7med-mahmoud** [comment]
@BlackFenix2 no I don't have a repo for that project.. I was starting that project and it was just giving me typescript errors evertwhere so I decided to recreate the project and see if it will give me the same error.

**Comment by BlackFenix2** [comment]
@a7med-mahmoud i made a PR https://github.com/bestguy/sveltestrap/pull/169 addressing both problems. thanks for providing the necessary type definition.

**Comment by bestguy** [comment]
Thanks all, merged and published in sveltestrap@3.7.3

**Comment by lucianoratamero** [comment]
I have one quick question about this, since I'm pretty new to typescript.

All typescript validations work fine if I import, for example, the Input component in a `<script lang="ts">` component:
![image](https://user-images.githubusercontent.com/1103672/95105645-d4238900-070d-11eb-81fd-06de3b2a4b00.png)

But if I follow the SSR suggestions from the docs by importing the component directly, I lose the typescript validation:
![image](https://user-images.githubusercontent.com/1103672/95105835-1947bb00-070e-11eb-9ef9-576afb5d0ff2.png)

Even svelte-check seems to ignore the error:
![image](https://user-images.githubusercontent.com/1103672/95105947-3bd9d400-070e-11eb-9dc7-2ce5dfc47302.png)

Is this something I'm doing wrong from being a noob?
Or a bug? If it's a bug, is it from this project, or from svelte-check/svelte language tools?

**Comment by bestguy** [comment]
Hi @lucianoratamero , that's a good question - I'd assume it would "just work", but I'm not sure.
I'll try myself locally and confirm I see same issue.

**Comment by bestguy** [comment]
Hi @lucianoratamero , it seems like we would first need to change the build to include the `@types` in the src dir, and then you would need to change your SSR imports to this style:

```html
<script lang="ts">
  import { Alert, Button, Jumbotron } from 'sveltestrap/src';
  // import Alert from 'sveltestrap/src/Alert.svelte';
  // import Button from 'sveltestrap/src/Button.svelte';
  // import Jumbotron from 'sveltestrap/src/Jumbotron.svelte';
</script> 
```

Let me see if can move the types or change build script, will update here

**Comment by bestguy** [comment]
Hi @lucianoratamero , can you please try this prerelease version and confirm this works?:
`npm install sveltestrap@3.9.1-2`

I think you will also need to change your ssr import style to:

```html
<script lang="ts">
  // import { Alert, Button, Jumbotron } from 'sveltestrap/src';
```

(You might need to restart your editor too after updating)
Please let me know if this works, and I can do a proper release.

**Comment by lucianoratamero** [comment]
hey, @bestguy, will do, first thing in the morning! thanks :)

**Comment by lucianoratamero** [comment]
yup, it works @bestguy ! I'm not sure how to validate the tree shaking for SSR, but the types now work perfectly :]
do you mind explaining what exactly was the issue? I'm using sveltestrap as a model for a design system implementation, and I'd like to apply the same solution there!

**Comment by bestguy** [comment]
Hi there, I'm not totally up on TypeScript and types resolution but we currently have a separate `@types` directory as part of the dist bundle, which we point to here: https://github.com/bestguy/sveltestrap/blob/master/package.json#L8.  
For some reason TS support or IDE does not correlate that for SSR imports.  So another convention people use is to intermix the *.d.ts files in the src dir, which seems to work fine in non-SSR and SSR cases:

```javascript
import { Alert, Button, Jumbotron } from 'sveltestrap';
```
and

```javascript
import { Alert, Button, Jumbotron } from 'sveltestrap/src';
```

Note however, it doesn't work for this style of SSR import:

```javascript
import Alert from 'sveltestrap/src/components/Alert.svelte';
```

but I think this is a decent compromise, unless/until we can find a better way to do this.
I'll create a PR with this change and update here with the new version.

**Comment by lucianoratamero** [comment]
hmmm, I see! :thinking:  I'll try this on my project, then, thanks :]

oh, another thing: just to remind you, this part of the readme is suggesting for people to use the type of SSR import that doesn't work with the types: https://github.com/bestguy/sveltestrap#note-on-server-side-rendering-ssr-usage-fixed
maybe updating these docs on the same PR is the best way to go!

**Comment by bestguy** [comment]
Yes thanks for reminder!  Good idea

**Comment by bestguy** [comment]
Hi @lucianoratamero, this was released in [sveltestrap@3.9.1](https://github.com/bestguy/sveltestrap/releases/tag/v3.9.1)
Let me know if you see any issues with it.

**Comment by bestguy** [comment]
Support should be good now!

**Comment by bestguy** [comment]
FYI for folks here, I'm attempting to update the types for v5.0.0 to the latest approach recommended:

https://github.com/bestguy/sveltestrap/pull/274/files#diff-afdae5db9835c2d2a3d5aee9bd7338d8f960fd39e4d720a26f94e199ad0aa3fb

Feel free to comment or review if you see anything off.
