### ISSUE TITLE
Svelte v3 compatibility

### ISSUE THREAD

**Issue by TheBosZ** [bestguy/sveltestrap#13]
Now that v3 of Svelte is out, are you interested in upgrading this library to be compatible?

I've [started a fork](https://github.com/TheBosZ/sveltestrap) to work on updating the components to be compatible with v3.

**Comment by jacwright** [comment]
I'm interested in v3 as well. I will check out your fork.

**Comment by bestguy** [comment]
Awesome @TheBosZ , would love to, just hadn't the time recently.  PRs very welcome!
