### ISSUE TITLE
Collapse / DropdownItem doesn't like store object

### ISSUE THREAD

**Issue by vfilatov** [bestguy/sveltestrap#130]
```svelte
{#if isLoggedIn}
	<TopNavBar/>
	<p>
		sample text
	</p>
{:else}
	<button on:click={() => User.signin()}>log in</button>
{/if}
```
The code above shows both (if && else) blocks if **_user_** in the next code
```svelte
<DropdownItem>{user}</DropdownItem}
```
is a 'svelte/store' object 
link to [REPL](https://svelte.dev/repl/d7b5f0d565a441cfac66e093ee6fe62d?version=3.19.1)

Please uncomment
```
	//const unUser = User.subscribe(v => user = v);
```
under **_TopNavBar.svelte_** tab

**Comment by vfilatov** [comment]
a workaround on App.svelte
```diff
2c2
< 	import { onDestroy } from 'svelte';
---
> 	import { tick, onDestroy } from 'svelte';
7c7
< 	const unUser = User.subscribe(v => user = v);
---
> 	const unUser = User.subscribe(async v => { await tick(); user = v});

```

**Comment by bestguy** [comment]
Hi @vfilatov ,

Sorry going through old issues and missed this.  This appears to be fine in v5:
https://svelte.dev/repl/d3c747a63ee14ccdadbef863e1e602a0?version=3.38.3

Will close, but please let me know if still an issue.
