### ISSUE TITLE
No data binding for component <Input type="select">

### ISSUE THREAD

**Issue by webcoder31** [bestguy/sveltestrap#131]
Hi,
Data binding does not work with component **Input type="select"**.
Here is an example showing the issue:

https://svelte.dev/repl/f7bf7a00940e428c85767bf6f0fc78d4?version=3.19.2

```
<script>
import { Input } from 'sveltestrap';

let selected = 'second';
</script>

<h1>SvelteStrap "select" data binding issue</h1>

<h2><strong>Bound variable value:</strong> {selected}</h2>

<h3>SvelteStrap select (&lt;Input type="select"&gt;)</h3>
<p>Not working: "Select" does not update the bound variable value and is not correctly initialized</p>
<Input type="select" id="select_component" name="select_component" bind:value={selected}>
	<option value="first">First item</option>
	<option value="second">Item that should be selected as initial value</option>
	<option value="last">Last item</option>
</Input>

<h3>Regular select (&lt;select&gt;)</h3>
<p>Working: "Select" correctly update the bound variable value and is correctly initialized</p>
<select id="select_html" name="select_html" bind:value={selected}>
	<option value="first">First item</option>
	<option value="second">Item that should be selected as initial value</option>
	<option value="last">Last item</option>
</select>
```

Looking at the SvelteStrap code I noticed that `bind:value` is missing in the implementation of the component.
https://github.com/bestguy/sveltestrap/blob/5dff47559e4101d1e38302f01b4253651196cd22/src/Input.svelte#L326

Thank you for sharing SvelteStrap ;)
Regards

**Comment by bestguy** [comment]
Hi @webcoder31 , 
This should be corrected with #133 , released in sveltestrap@3.3.3

Can you please confirm and update this issue?

**Comment by webcoder31** [comment]
Hi @bestguy ,
The data binding works fine now.
Thank you for very fast support ;)
Best regards

PS: Got this warning in console `<Input> was created without expected prop 'readonly'`. Is `readonly` a mandatory attribute ?

**Comment by bestguy** [comment]
Weird, not sure!  Thanks for the heads up, will look

**Comment by x80486** [comment]
There is one more thing: if the value is `undefined` initially, the `Input` component (of type `select`) is not picking up the first value. I can confirm this works as expected if the HTML `select` element is used instead.

**Comment by bestguy** [comment]
Looks to be working correctly in v5: https://svelte.dev/repl/5bcf210db26e42fda6faa0b31beab47a?version=3.38.3

Please comment if still seeing issues.
