### ISSUE TITLE
Componentize all SCSS

### ISSUE THREAD

**Issue by btakita** [bestguy/sveltestrap#14]
To make the payload as light as possible, it would be beneficial to componentize all SCSS.

The bootstrap *.scss libraries can be encapsulated within a component that uses global styles. The https://www.npmjs.com/package/@ctx-core/sass package has a sass/scss & global css preprocessor.

This could be the bootstrap base component:

```html
<!--src/Bootstrap.svelte-->
<style type=text/scss global>
	@import '~bootstrap/scss/variables';
	// ...
</style>
```

```html
<!--src/Grid.svelte-->
<script>
	include Bootstrap from './Bootstrap.svelte'
</script>
<Bootstrap></Bootstrap>
<style type=text/scss global>
	@import '~bootstrap/scss/mixins/grid';
	// ...
</style>
```

This could be a widget (e.g. carousel):
```html
<!--src/Carousel.svelte-->
<script>
	include Grid from './Grid.svelte'
</script>

<Grid></Grid>
<!--Rest of Carousel.svelte template-->

<style type=text/scss global>
	@include "~bootstrap/scss/mixins/carousel"
</style>
```

**Comment by btakita** [comment]
Related discussions:

https://github.com/sveltejs/svelte/issues/1070

https://github.com/sveltejs/svelte/issues/379

**Comment by bestguy** [comment]
Looks interesting, thanks @btakita .  
When I started the project, one of the main usecases was to allow for external Bootstrap theming (for example https://www.bootstrapcdn.com/bootswatch/).  

This encapsulation would embed only one particular Bootstrap theme though?

**Comment by TheComputerM** [comment]
In order to use external styles or scss variables, a lot more setup will be required on the users end. [svelte-materialify](https://github.com/TheComputerM/svelte-materialify) allows for variable customization but that comes at a heavy cost needed for users to install `sass svelte-preprocess postcss`. Is there any simpler way to achieve this?

**Comment by bestguy** [comment]
Decided to close this as we'll likely stick to external CSS for this library.
