### ISSUE TITLE
CustomInput - Checkbox and others

### ISSUE THREAD

**Issue by arthurgermano** [bestguy/sveltestrap#140]
Hi Guys.. How are you ?
Nice work you have been done.. Congrats!!

But I don't know if there is a limitation or something that breaks.. but
Why did you omit events from CustomInput like checkbox ?
Because I think was very necessary and they emit perfectly.. look the snippet below
I just added and test two events but I think you should emit all possible don't you agree ?
Sorry if I am missing something..
CustomInput.svelte
`{:else if type === 'switch' || type === 'checkbox'} 
div class={wrapperClasses}>
    <input
      {id}
      type="checkbox"
      class={customControlClasses}
      bind:checked
      on:change
      on:click
      {name}
      {disabled}
      {placeholder}
      {...props} />
    <label class="custom-control-label" for={labelHtmlFor}>{label}</label>
    <slot 
  </div`

Sorry for the snippet I couldn't find a better way to format..
Thanks in advance..

**Comment by bestguy** [comment]
Hmm, thanks @arthurgermano , that is probably an oversight, we didn't have good event support when we first moved to Svelte 3.x, and might have missed.  I'll take a look!
