### ISSUE TITLE
Console warning: <Input> was created without expected prop 'readonly'

### ISSUE THREAD

**Issue by vfilatov** [bestguy/sveltestrap#144]
Why 'readonly' attribute would be mandatory?

https://svelte.dev/repl/bf1eb9d9a5ee44f5ab1fdfbe823a5f7b?version=3.20.1

```svelte
<script>
  import { Input } from 'sveltestrap';
</script>

<p>
  console says:
  <br>
  <i>"&lt;Input&gt; was created without expected prop 'readonly'"</i>
</p>
<Input />
```

**Comment by vfilatov** [comment]
```svelte
<Input type="select" readonly={false}>
```
causes disabled background color.
without readonly prop throws the warning above to console.

https://svelte.dev/repl/bf1eb9d9a5ee44f5ab1fdfbe823a5f7b?version=3.22.2

**Comment by bestguy** [comment]
Correct in [v3.9.2](https://github.com/bestguy/sveltestrap/releases/tag/v3.9.2) and later versions, thanks for the heads up.
