### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by dstaley41** [bestguy/sveltestrap#145]
If anyone else was looking for a more reasonable way to use bootstrap4's icons, I tossed together this rough idea. explanation inside on how to populate the mapping object needed. Hope it saves someone else some of the frustration these icons come with.. 

usage: <BootstrapIcon icon="alarm" />

https://gist.github.com/dstaley41/495dca87a04d168519a57c93a040c86e

**Comment by bestguy** [comment]
Oh nice!  Thank you, this is a good addition to v5

**Comment by bestguy** [comment]
Hey @dstaley41 , I've added an Icon component to simplify this further:
https://sveltestrap.js.org/?path=/story/components--icon

Thanks for the idea, let me know if you see any issues with it.
