### ISSUE TITLE
Bootstrap 5 direction?

### ISSUE THREAD

**Issue by BenHayat** [bestguy/sveltestrap#156]
Hi;
Firstly, I'd like to thank you for your work.
Is there plan to port your library to BS5, when it goes public?

Thanks!
..Ben

**Comment by bestguy** [comment]
Hi @BenHayat , yes the intent is to support Bootstrap 5, and have at least have beta versions available by Bootstrap beta 1.(Currently alpha 1 as I type this).
From my experience with Bootstrap v4, alpha versions can and do change a lot, so I'm reluctant to do _too_ much work prematurely and have a lot of churn, but any help here is appreciated if people are using v5 with this.

From a quick look using v5 CSS with Sveltestrap docs, most everything seems okay.  Two noticeable issues are InputGroups and CustomInputs.  I'll hopefully have more time soon to start a v5-dev branch and can start tracking more formally.

**Comment by bestguy** [comment]
Hi @BenHayat and others interested, I've strated a V5 branch: 
https://github.com/bestguy/sveltestrap/compare/v5?expand=1

Seems straightforward so far, so I will try to finish compatibility with Bootstrap 5 Alpha 1 and do an alpha release of  sveltestrap v5 in next couple weeks

**Comment by bestguy** [comment]
We nearing completing of v5 alpha 3 parity: https://github.com/bestguy/sveltestrap/compare/v5?expand=1

but still missing Form changes that impact FormGroup, Labels & Inputs.  Hopefully should be ready for an alpha 3 pre-release this weekend or next week.

**Comment by mmrath** [comment]
@bestguy Is it possible to publish the alpha versions of sveltestrap supporting bootstrap v5 alpha?

**Comment by bestguy** [comment]
Hi @mmrath, yes, however I'd like to complete alpha3 parity (forms and inputs are currently in progress). I hope to have a pre-release this weekend

**Comment by bestguy** [comment]
@mmrath  @BenHayat and others, we've published sveltestrap@5.0.0-alpha.3 which should give parity to Bootstrap 5 alpha 3.

To try, please note you'll need to `npm install sveltestrap@5.0.0-alpha.3` 
Specify the exact version when installing, as these have a `beta` tag.

You'll also need to include Bootstrap v5 as your CSS such as: `https://v5.getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css`, 
since there are breaking changes in Bootstrap, and will not look right using v4 Bootstrap.  I'll write up release notes soon on the details.

There are likely bugs so please let us know if you find any.

**Comment by bestguy** [comment]
Updated to `sveltestrap@5.0.0-alpha.3-1` to update to latest Bootstrap alpha 3 parity

**Comment by bestguy** [comment]
Updated to `sveltestrap@5.0.0-alpha.3-2` to update to correct some issues.

`npm install sveltestrap@5.0.0-alpha.3-2`

**Comment by bestguy** [comment]
Updated to sveltestrap@5.0.0-alpha.3-3 to add [Accordion](https://getbootstrap.com/docs/5.0/components/accordion/)

`npm install sveltestrap@5.0.0-alpha.3-3`

**Comment by kefahi** [comment]
Hello @bestguy 
Thank you for the job well done!
I'm interested in BS5 beta due to the RTL support. 
I was wondering if you started working on updating the V5 branch to support BS5 Beta. 
Please let me know if help is needed. I would at least help with testing as an early adopter in my multi-lingual CMS. 
Regards,

**Comment by bestguy** [comment]
Hello @kefahi ,

Yes we are mostly compatible with beta 1, there was just a change to the utility class names and I have a PR for that.  I will try and release beta 1 this weekend.

**Comment by bestguy** [comment]
Hi @kefahi,
We've published `sveltestrap@5.0.0-beta.1` which should include the new RTL changes.  Please try out and let me know if you see any issues.

**Comment by bestguy** [comment]
We've published sveltestrap@5.0.0-beta.1-1 which now includes Popover and Tooltip updates from v4.

**Comment by bestguy** [comment]
We've published sveltestrap@5.0.0-beta.1-2 which now includes Popover fixes and now includes Bootstrap Icon support

**Comment by kefahi** [comment]
> We've published sveltestrap@5.0.0-beta.1-2 which now includes Popover fixes and now includes Bootstrap Icon support

Thank you for the amazing work!

I tried the latest version on a simple setup and came across two issues. 
1. InputGroupAddon is missing entirely. Is this intentional? if so what is the alternative.
2. Bootstrap Icons are loaded via hardcoded link. I would rather leave this to the developer to decide (in the same way how bootstrap css files are served). 

Please let me know if you want me to open tickets. 

Once again, thank you!

**Comment by bestguy** [comment]
Hi @kefahi, yes regarding 1, these have been removed in Bootstrap v5: https://getbootstrap.com/docs/5.0/forms/input-group/
Order comes from the children you put in the InputGroup. InputGroupAddon container is no longer needed.

On 2, hmm yes that might be better, although unlike bootstrap css there is no "themes" for icons.  Let me look at this over next days, and creating issue is fine for this one for tracking.

**Comment by bestguy** [comment]
We've published sveltestrap@5.0.0-beta.1-4 which now includes Row `cols` support.

**Comment by kefahi** [comment]
Hello, I wanted to let you know that the more recent `bootstrap 5.0.0-beta2` is working with `sveltestrap 5.0.0-beta.1-4` without any noticeable issues.

**Comment by bestguy** [comment]
Ah thank you!  I'll look at their release notes

**Comment by bestguy** [comment]
We've released `sveltestrap@5.0.0-beta.3` to match Bootstrap v5 beta 3.
Adds the new Offcanvas component and numbered ListGroup.

**Comment by bestguy** [comment]
Released `sveltestrap@5.0.0-beta.3-1` to pick up some corrections to Tooltips, Popover, & Dropdown released on master.

**Comment by bestguy** [comment]
Released `sveltestrap@5.0.0-beta.3-2` to pick up additional corrections released on master and to remove deprecated Uncontrolled* components.

**Comment by nstuyvesant** [comment]
Since Bootstrap 5 was released a few days ago, how have things been looking with sveltestrap@5.0.0-beta.3-2?

**Comment by bestguy** [comment]
Great, I'll look over it any changes and publish v5 official this weekend.  I will also ensure v4 docs are available as many apps will take time to upgrade Bootstrap

**Comment by bestguy** [comment]
Sveltestrap 5 has been released! 🎉 
https://github.com/bestguy/sveltestrap/releases/tag/v5.0.0

Please try v5.0.0 out and start a new issue if you experience any problems.
`npm install sveltestrap@5`

Thank you all for the use and help!

**Comment by kefahi** [comment]
@bestguy Awesome news! thank you.

Here is a simple bi-lingual CMS website (Arabic/English) I built on Svelte/Bootstrap5/Sveltestrap. It is still under active development. 
RTL is working really nice; the language switching widget is at the bottom (footer). 

https://demo.imx.sh/

**Comment by bestguy** [comment]
Lovely!  Nice work friend, glad you are able to put this to good use.
