### ISSUE TITLE
Svelte 3.24.0 seems to have broken input value binding

### ISSUE THREAD

**Issue by d0x2f** [bestguy/sveltestrap#157]
With two input fields in the same component, changing one seems to clear the others.

See this REPL for an example: https://svelte.dev/repl/a3a78cc7744b4b4fb4a1b4a752e9a2d3?version=3.24.0

There are a couple of `<input>` related PRs included in svelte 3.24.0:

 - https://github.com/sveltejs/svelte/pull/5004 
 - https://github.com/sveltejs/svelte/pull/5028

**Comment by bestguy** [comment]
Yikes that's nasty, thanks for the heads up @d0x2f .  There's some delay with response due to covid situation, but catching up here, is a general fix forthcoming with svelte, or does this call into question our usage of $$props?

**Comment by valent-novem** [comment]
Edit `Input.svelte`, replace line 27 with this:
`const { type: _omitType, color: _omitColor, value: _omitValue, ...props } = clean($$props);`
Seems like it will fix the problem

**Comment by bestguy** [comment]
Thanks, let me try this out and look for other instances

**Comment by d0x2f** [comment]
Thanks @bestguy,

To your original question, I'm not too certain on what the behaviour of the proposed svelte PR will have in this case, I'm not familiar enough with the svelte code to tell.

A svelte dev mentioned the relatively new $$restProps var, which is the same as $$props but omits any keys that are exported by the component.
So in this case, since 'value' is exported, $$restProps will omit it by default.

This seems like the right approach to me.

**Comment by bestguy** [comment]
> relatively new $$restProps var, which is the same as $$props but omits any keys that are exported by the component.

Nice! that $$props omit stuff was a pain

**Comment by bestguy** [comment]
An update is moving to `$$restProps` seems to clear issue, but 3.24.0 also breaks Inputs type="select" altogether, I need to correct that prior to merge.

**Comment by bestguy** [comment]
Hey @d0x2f , this should be corrected in sveltestrap@3.5.0, please update/close this issue if corrects for you.
Thanks for the heads-up

**Comment by d0x2f** [comment]
Thanks so much @bestguy, it works great. The REPL is fixed now as well.

:beers:
