### ISSUE TITLE
Re: the install instructions

### ISSUE THREAD

**Issue by tleylan** [bestguy/sveltestrap#162]
Sorry to bother you but the docs say:  npm install --save svelte sveltestrap
This installs svelte and sveltestrap correct? Is it necessary to install svelte again? Thanks.

**Comment by bestguy** [comment]
If you already have svelte, it's not necessary to reinstall.  We mention installing svelte because it's a peerDependency and not installed automatically.

**Comment by tleylan** [comment]
Thank you.
