### ISSUE TITLE
Getting "component is null" error message on the console log

### ISSUE THREAD

**Issue by kefahi** [bestguy/sveltestrap#168]
Hi,
First of all thank you for the great library, it really makes a huge difference!

I faced one specific problem with dealing with Dropdown menus, both regular and Uncontrolled. 

Following the examples in https://sveltestrap.js.org give the following error:

Uncaught TypeError: component is null
    handleDocumentClick Dropdown.svelte:85

Looking at the code in Dropdown.svelte I indeed see a component variable declared `let component;` but was never assigned value. 

Any help is appreciated.

Keep it up!

**Comment by bestguy** [comment]
Hi @kefahi , thanks.

I'm unable to duplicate, here is sample using same code: https://svelte.dev/repl/4b7f32465b2c4980b9540d8b6ba23fde?version=3.24.0

Would you mind sharing the code you are using?

**Comment by kefahi** [comment]
Thank you @bestguy 
The error went away on its own. It could be a glitch in my local setup. 
But I'm now curious to understand how it works without errors given that the component variable in Dropdown.svelte is not assigned any value.
Thank you again for following up.

**Comment by bestguy** [comment]
Hi @kefahi ,
I think it actually is assigned a value on line [#97](https://github.com/bestguy/sveltestrap/blob/127f6aa8c7c6baf09b147baf08b7b70b5b2ebccc/src/Dropdown.svelte#L97)

by using: `bind:this={component}`

https://svelte.dev/tutorial/bind-this

**Comment by kefahi** [comment]
@bestguy 
That clarifies it, many thanks for your patience and follow-up!
I'm closing the ticket.
