### ISSUE TITLE
Empty IDs invalidate HTML markup

### ISSUE THREAD

**Issue by Shackless** [bestguy/sveltestrap#174]
Sveltestrap components like Container, Row etc. generate an empty `id=""` attribute on DOM nodes which is invalid according to the [W3C spec](https://www.w3.org/TR/html4/types.html#type-id). It would be great if this empty attribute could just be omitted if it's not set.

**Comment by bestguy** [comment]
Hey thanks for the heads up, yeah we are doing this in a lot of places:

```javascript
export let id = '';
```

Should be an easy fix, will PR and update by this weekend hopefully.

**Comment by bestguy** [comment]
Hi @Shackless , this was super easy, should be fixed in #175 , published as sveltestrap@3.7.4

Will close, let me know if you still see issues

**Comment by Shackless** [comment]
Cool, thanks for the super-fast resolution. It works perfectly now!

**Comment by Shackless** [comment]
I just noticed that the sveltestrap components now render with `id="undefined"` instead of `id=""`. Interesting is that Chrome doesn't display the id attributes when inspecting an element but if you select "View Page Source" instead, you'll see them. Check https://shipbit.de as live example. It uses latest sveltestrap and Sapper packages. I'm not sure if this issue might be related to the latter.

**Comment by bestguy** [comment]
Hey there, hmm, that's super annoying, I only confirmed in the inspect elements.  
Explicitly declaring id="" predates the {...$$restProps} stuff which was not initially supported by Svelte...
I'll reopen and look this weekend. I think the restProps should cover!

**Comment by bestguy** [comment]
Should be corrected by #177 , published as sveltestrap@3.7.6
I think in upcoming v5 we'll prune out all the HTML props we just pass through

**Comment by Shackless** [comment]
Thanks again and nice, now it definitely works! 
I have another suggestion: Instead of using invalid attributes like `md="3"` on `Col`s, one could use `data-md="3"` to make it W3 valid. I can take a look at this and create a PR when I find the time and if you're interested in that.

**Comment by bestguy** [comment]
Those props "shouldn't" be ending up in the DOM, hopefully you aren't seeing those.

That is an interesting idea, but this lib mostly modeled its interface after a React Bootstrap library that uses these non-data prop names, which echos Bootstrap's class naming.  Would be reluctant to change, but if you have a sample you are thinking of could post here.

**Comment by bestguy** [comment]
Closing, fixed in v3.7.6
