### ISSUE TITLE
Dropdown menu does not open in a Navbar

### ISSUE THREAD

**Issue by jonjes** [bestguy/sveltestrap#187]
When you click on a dropdown component in a navbar, the dropdown menu does not open.

You can also test this on the Sveltestrap Navbar component page:
https://sveltestrap.js.org/?path=/story/components--navbar
To test, click on the "Options" dropdown.

But otherwise, great work on this project.

**Comment by Msimoneau** [comment]
Hi @jonjes,
Same here for sveltestrap version 3.8.1. I've found a simple workaround that's working for me. Uninstall (npm uninstall sveltestrap) and reinstall version 3.7.3 (npm install sveltestrap@3.7.3 --save-dev).

**Comment by Msimoneau** [comment]
Hi @bestguy,

It seems the commit(0d6c1f0) makes the Dropdown menu in navBarMenu stop working.
The addition of the style "overflow: hidden;" to the Collapsable.svelte div prevent the menu from opening.
I've locally reverted this commit in my version 3.9.3, and it's working fine.

Thanks for svelvtestrap !!

**Comment by vfilatov** [comment]
> Hi @bestguy,
> 
> It seems the commit([0d6c1f0](https://github.com/bestguy/sveltestrap/commit/0d6c1f0ec695168abfb13d4696ad3b67a32fdf0f)) makes the Dropdown menu in navBarMenu stop working.
> The addition of the style "overflow: hidden;" to the Collapsable.svelte div prevent the menu from opening.
> I've locally reverted this commit in my version 3.9.3, and it's working fine.
> 
> Thanks for svelvtestrap !!

Yes, that is the workaround!
Thank you, @Msimoneau !

**Comment by bestguy** [comment]
Oh!  Thank you @Msimoneau - I completely forgot that was related, will revert and find a better fix for that!

**Comment by bestguy** [comment]
Should be fixed by #199 , published in [sveltestrap@3.9.4](https://github.com/bestguy/sveltestrap/releases/tag/v3.9.4) Thanks all for the heads up on the issue.

**Comment by bestguy** [comment]
Closing, let me know if not resolved.

**Comment by jonjes** [comment]
Yes, it works great now.  Many thanks to you and @Msimoneau for the fix!
