### ISSUE TITLE
CustomInput type="radio" events don't work.

### ISSUE THREAD

**Issue by Florian-Schoenherr** [bestguy/sveltestrap#188]
`<CustomInput type="radio" id="someId" name="someName" label="Something"
on:input={() => console.log("doesn't work")}
on:blur={() => console.log("doesn't work")}
on:change={() => console.log("doesn't work")} />`

If it's something on my side, please tell me.

**Comment by bestguy** [comment]
Hi @Florian-Schoenherr ,
Hmm that's strange, I thought was covered here: https://github.com/bestguy/sveltestrap/blob/master/src/CustomInput.svelte#L106

Let me try and duplicate locally, thanks for heads up.

**Comment by bestguy** [comment]
Hi @Florian-Schoenherr ,

This seems to work for me locally, I added your sample to the storybook and see:

<img width="420" alt="Screen Shot 2020-09-28 at 8 39 56 AM" src="https://user-images.githubusercontent.com/405608/94454111-53d9b280-0166-11eb-8859-e0003097d4f2.png">

Could you confirm how you are importing and also check if your console filters are eating the events?

**Comment by Florian-Schoenherr** [comment]
My bad! I just didn't update to the newer version. I've even seen [this](https://github.com/bestguy/sveltestrap/blob/master/src/CustomInput.svelte#L106) on github but thought I already have it.
Well, guess I'll close this, sorry for wasting time..

**Comment by bestguy** [comment]
Ah no worries, glad issue is fixed.
