### ISSUE TITLE
Icon.svelte required Typescript enabled in Svelte project

### ISSUE THREAD

**Issue by crazedVic** [bestguy/sveltestrap#189]
Currently:
"sveltestrap": "^3.8.1"
and
"svelte": "^3.28.0"

I just wanted to update my Svelte project from 3.20.1 and svelte-strap 3.3.3 and my project would no longer run.  Took a bit but the error was coming from:
node_modules/sveltestrap/src/Icon.svelte
Error: Cannot find module 'typescript'

which has this:
```
<script lang="ts">
  import classnames from './utils';
  export let name = undefined;
  export let size = '1rem';
  export let color = undefined;
  export let url = 'https://cdn.jsdelivr.net/gh/twbs/icons/icons/';
  let className = undefined;
  export { className as class };

  $: classes = classnames(
    'bi',
    color ? `text-${color}` : false,
    className
  );
</script>
```

Because I am not using Typescript in this ongoing project nor do i have plans to add Typescript later, please let me know what the last version of svelte-strap was that worked without requiring Typescript.

**Comment by crazedVic** [comment]
Looks like Icon.svelte was added recently via pull request from bestguy:

https://github.com/bestguy/sveltestrap/blob/v3.8.0/src/Icon.svelte

Doing a quick search it appears that this project will require Typescript going forward?

What's the plan?

**Comment by bestguy** [comment]
Hi @crazedVic , sorry the intention was not to require downstream TS unless doing the SSR src include (where transpilation is handled by user).  Can you confirm how you are importing the sveltestrap components?

In any case, this Icon component is causing other troubles too, I think I'll revert and release a new version.

**Comment by bestguy** [comment]
Hi @crazedVic , this has been reverted in #190 and released as sveltestrap@3.9.0

Let me know if this corrects issue, thanks for heads up.

**Comment by crazedVic** [comment]
i was adding svelte-strap using npm.  I will update and see how it goes.  thanks!

**Comment by bestguy** [comment]
Cool, thanks for update, I'll close and feel free to reopen if you see any issues.
