### ISSUE TITLE
Input readonly prop

### ISSUE THREAD

**Issue by quasarchimaere** [bestguy/sveltestrap#197]
afaik the readonly is a parameterless property and thus adding the default readonly prop will result in `readonly="false"` to be added to the html input tag. which causes the default bootstrap css to be applied to the input making it look disabled

sveltestrap version: 3.9.2
did not happen in: 3.9.0

**Comment by bestguy** [comment]
Oops, yes you are correct.  Will patch

**Comment by bestguy** [comment]
Corrected in [sveltestrap@3.9.3](https://github.com/bestguy/sveltestrap/releases/tag/v3.9.3), thanks for the heads-up

**Comment by quasarchimaere** [comment]
just tried it with 3.9.3 and it works as intended, thanks!
