### ISSUE TITLE
DropdownToggle color attribute refers wrong Color enum with outline styles

### ISSUE THREAD

**Issue by schamane** [bestguy/sveltestrap#202]
What i would like to do:

```
<script lang="ts">
    import {Color} from 'sveltestrap'
    const outlineSecondary = Color.outlineSecondary;
</script>
<DropdownToggle caret color={outlineSecondary}>
```

But colors doesn't support outlined ;(

**Comment by bestguy** [comment]
Hi @schamane, since DropdownToggle extends Button by default, outline is not a color, it's a boolean prop:

```javascript
<DropdownToggle caret outline color={outlineSecondary}>
```

https://github.com/bestguy/sveltestrap/blob/master/src/DropdownToggle.svelte#L76

**Comment by schamane** [comment]
Ou, sorry, i wasn't found it my way. Thanks a lot. Great project!

`<DropdownToggle caret outline color="secondary">`
