### ISSUE TITLE
Lazy load images

### ISSUE THREAD

**Issue by PaulEbose** [bestguy/sveltestrap#206]
I don't know how opinionated this might be _or_ the repercussions in some use cases 
but it would be nice to lazy load images by default

**Comment by bestguy** [comment]
Hi @PaulEbose , that's an interesting idea, do you mean in Carousel?
I'm not sure of any other direct usages of img tags

**Comment by PaulEbose** [comment]
Yesss. I initially thought there were more image tags in other places. I search the repo and saw about 6 results, 4 of which are in Carousel Item components 


https://github.com/bestguy/sveltestrap/search?p=1&q=%3Cimg

**Comment by bestguy** [comment]
Cool thanks, actually now that I'm looking at the Carousel code, we don't wrap the `<img>` tag in a component, and user just passes in:

```html
<Carousel {items} bind:activeIndex>
  <div class="carousel-inner">
    {#each items as item, index}
      <CarouselItem bind:activeIndex itemIndex={index}>
        <img src={item} class="d-block w-100" loading="lazy">
      </CarouselItem>
    {/each}
  </div>
</Carousel>
```

So you can enable lazy loading that way without needing to change any Carousel components

**Comment by PaulEbose** [comment]
Yeah, this is true. Thank you! 

Also, another reason I opened this issue is because I wanted to use the `Media` component to _lazy load_ an image. There was no intellisense in vscode so I came here digging for answers. 

> Hi @PaulEbose , that's an interesting idea, do you mean in Carousel?
> I'm not sure of any other direct usages of img tags

I meant to also refer to this https://github.com/bestguy/sveltestrap/blob/master/src/Media.svelte#L51
If it is loaded lazily by _default_ or a prop is used

**Comment by bestguy** [comment]
Ah, yes that one does wrap an img, however we support restProps and you can do this:

```html
<Media>
  <Media left href="#">
    <Media
      object
      src="https://via.placeholder.com/64x64.png?text=64%C3%9764"
      loading="lazy"
  />
  </Media>
  <Media body>
    ...
  </Media>
</Media>
```

**Comment by PaulEbose** [comment]
Okay, thank you very much
