### ISSUE TITLE
Dropdown in table is hidden by table border

### ISSUE THREAD

**Issue by hcrohland** [bestguy/sveltestrap#210]
Hi,

I am toogling a dropdown within a table. The dropdown will only display within the table range. I can scroll the table to see the rest.

I think it should not be rendered within the table but in the window.

This might be similar to  #199 

Best,
Christoph

**Comment by bestguy** [comment]
Hi @hcrohland, could you share a code sample?  Could alto be issue with table responsive CSS.

**Comment by hcrohland** [comment]
Yes exactly. It only happens with a responsive table:
https://svelte.dev/repl/3208d980faca4c288d6f2a08186a7722?version=3.30.0

**Comment by bestguy** [comment]
Thanks, looking if can fix in components at we are currently not using popper.js to position these

**Comment by bestguy** [comment]
Closing, please comment or reopen if not working as expected
