### ISSUE TITLE
Components size

### ISSUE THREAD

**Issue by zfranco55** [bestguy/sveltestrap#211]
As in bootstrap it is possible to change the size of the components like small, default large?

**Comment by bestguy** [comment]
Hi @zfranco55 , yes it is, we have props for that in components like Button and Table.  Which are you looking at that does not?

**Comment by zfranco55** [comment]
Table

Il giorno lun 21 dic 2020 alle ore 23:21 bestguy <notifications@github.com>
ha scritto:

**Comment by bestguy** [comment]
Ah, yes we do support size, just missing from docs:

`<Table size="lg">...</Table>`
`<Table size="sm">...</Table>`

I'll update the Table doc samples to make this clearer

**Comment by zfranco55** [comment]
I also meant as height of the table rows, which in boostrap the table
propity is defined as: "small"

Il giorno mar 22 dic 2020 alle ore 19:03 bestguy <notifications@github.com>
ha scritto:

**Comment by bestguy** [comment]
.table-sm and .table-lg (on the Table) control this as far as I know.  The size prop above sets those on the table

**Comment by zfranco55** [comment]
Ok, thanks.

Il giorno mer 23 dic 2020 alle ore 01:24 bestguy <notifications@github.com>
ha scritto:
