### ISSUE TITLE
TabContent / TabContext / TabPane - shared state for all instances

### ISSUE THREAD

**Issue by kenhorn** [bestguy/sveltestrap#212]
I'm just learning Svelte and Sveltestrap -- thanks for a great lib on a great tool, has made me productive and eased the migration to adoption w bootstrap (also learning..).

In my UI naivety (I'm no UX designer), I wanted to put multiple tab components (whether tabs or pills, horz or vert) on the same page. However, the tab state for activeTabId is held in a shared writable store. Is it possible to adopt similar?

I've built an alternative in the meantime (still using Nav, NavItem, NavLink) - using a container element so that getContext/setContext can be used. Happy to donate is useful (I'm probably losing a bunch of flexibility, since I'm fixing the nav UI rather that two named slots, say). It has a reduced footprint as the nav items are passed as lightweight array.

**Comment by bestguy** [comment]
Hi @kenhorn , ah you are correct, that is wrong behavior in sveltestrap.  We should be able to have multiple tab panes on same page.  We'll look at this to correct soon

**Comment by bestguy** [comment]
Hi @kenhorn , this should be corrected by #213, and was released in `sveltestrap@3.9.7`.

Please confirm and can close the issue.

**Comment by kenhorn** [comment]
That fixes it -- though I'm not clear on the correct tab example -- I've
put my test below.   Also, have added my own tab impl, which is similar but
compact (but not fully bootstrap compliant etc).

Thanks for the fast fix and release!

<script>
import { Nav, NavItem, NavLink, TabPane, TabContent } from "sveltestrap";
let activeTabId1 = "x";
let activeTabId2 = "y";
</script>
<div class="row pt-2">
<div class="col-sm">
<Nav tabs>
<NavItem>
<NavLink active={activeTabId1 == "x"} on:click={()=>activeTabId1 = "x"}>X1</
NavLink>
</NavItem>
<NavItem>
<NavLink active={activeTabId1 == "y"} on:click={()=>activeTabId1 = "y"}>Y1</
NavLink>
</NavItem>
</Nav>
<TabContent activeTab={activeTabId1}>
<TabPane tabId="x">
x1x1
</TabPane>
<TabPane tabId="y">
y1y1
</TabPane>
</TabContent>
</div>
</div>

<div class="row pt-2">
<div class="col-sm">
<Nav tabs>
<NavItem>
<NavLink active={activeTabId2 == "x"} on:click={()=>activeTabId2 = "x"}>X2</
NavLink>
</NavItem>
<NavItem>
<NavLink active={activeTabId2 == "y"} on:click={()=>activeTabId2 = "y"}>Y2</
NavLink>
</NavItem>
</Nav>
<TabContent activeTab={activeTabId2}>
<TabPane tabId="x">
x2x2
</TabPane>
<TabPane tabId="y">
y2y2
</TabPane>
</TabContent>
</div>
</div>



Example
<script>
import TabPanel from "./TabPanel.svelte";
import TabNav from "./TabNav.svelte";
let activeTabId = "A";
let ids = ["A", "B"].map((x) => ({id:x,label:x}));
</script>
<div class="row pt-2">
<div class="col-sm">
<TabNav items={ids} bind:activeTabId tabs={false} >
<TabPanel tabId="A">
AA
</TabPanel>
<TabPanel tabId="B">
BB
</TabPanel>
</TabNav>
</div>
</div>

TabNav
<script>
import {Nav, NavItem, NavLink} from 'sveltestrap';
import { setContext } from 'svelte';
import { writable } from 'svelte/store';

const ctxKey="TabPanelStack";
let atw = writable(activeTabId);
setContext(ctxKey, atw);
$: {
atw.set(activeTabId);
}
</script>

<div class={tabclass} id={tabclass} >
<Nav tabs={tabs} pills={!tabs} {...$$restProps}>
{#each items as item}
<NavItem>
<NavLink active={activeTabId == (item.id || item.label)} on:click={()=>
activeTabId = (item.id || item.label)}>{item.label}</NavLink>
</NavItem>
{/each}
</Nav>
<slot />
</div>

TabPanel
<script>
export let tabId = "unset";

import { getContext } from 'svelte';

let activeTab = "";
getContext('TabPanelStack').subscribe(value => activeTab = value);

</script>
<div style="display: {tabId === activeTab ? 'block':'none'}">
<slot ></slot>
</div>

**Comment by bestguy** [comment]
Thanks, yeah that's a good idea, I think these components should be simplified for this usage.  We are prepping v5 and will look at adding something like this.

**Comment by bestguy** [comment]
Hi @kenhorn ,

Just FYI that TabContent and TabPane were reworked in Sveltestrap v5 to make the usage a lot easier.
Would be helpful if you'd like to take a look and comment: https://sveltestrap.js.org/?path=/story/components--tabs
