### ISSUE TITLE
Change Tooltip isHover

### ISSUE THREAD

**Issue by eddie0329** [bestguy/sveltestrap#219]
Currently tooltip impented as follow: 

```javascript
export let debugHover = false;
let isHover = false;
```

Proposed:

```javascript
export let isHover = false;
```

How about the proposed version tooltip like popover? @bestguy 
debugHover was for testing reasons. But I think this does not needed when isHover exposed. And exposing isHover can enable user more flexible.

**Comment by bestguy** [comment]
Good idea @eddie0329 , updated with #220
