### ISSUE TITLE
Trouble creating a Nav tabs

### ISSUE THREAD

**Issue by bschwarz** [bestguy/sveltestrap#233]
"sapper": "^0.28.0",
"svelte": "^3.32.2"
"sveltestrap": "^3.13.0"

I am not sure what I am doing wrong. I am using Sapper/Svelte. I have the below code:

```
<Nav tabs fill>
	<NavItem active>
		<NavLink data-toggle="tab" href="#sequence">sequence</NavLink>
	</NavItem>
	<NavItem active>
		<NavLink data-toggle="tab" href="#deployment">deployment</NavLink>
	</NavItem>
</Nav>
<TabContent activeTab="sequence">
	<TabPane id="sequence" tabId="sequence" class="fade"> 
		<h3>SEQUENCE</h3>
	</TabPane>

	<TabPane id="deployment" tabId="deployment" class="fade">
		<h3>DEPLOY</h3>
	</TabPane>
</TabContent>
```

When I inspect the render page, it comes to this:
```
<div id="sapper">

<main class="svelte-19nwrvr">
    <ul class="nav nav-tabs nav-fill">
        <li class="nav-item active">
            <a data-toggle="tab" href="#sequence" class="nav-link">sequence</a>
        </li>
        <li class="nav-item">
            <a data-toggle="tab" href="#deployment" class="nav-link">deployment</a>
	</li>
    </ul>
    <div class="tab-content">
        <div id="sequence" class="tab-pane fade active">
            <h3>SEQUENCE</h3>
        </div>

	<div id="deployment" class="tab-pane fade">
            <h3>DEPLOY</h3>
        </div>
    </div>
</main>
</div>
```
This seems correct, at least per the bootsrap docs. 

When the page is rendered, the tabs show up, but neither are active and when I click on them, neither one shows the content. I have tried with and without _data-toggle_ for the 'a' tags, but same experience. 

Am I missing something?

**Comment by bestguy** [comment]
Hi, hmm let me look locally.   One quick observation is you should only have active on one item, and you have multiple.

**Comment by bestguy** [comment]
Hi @bschwarz,

Looking at your example, I noticed a few things.  
- The  main one is sveltestrap `Nav` and `TabContent` don't use the `data-` attributes and Bootstrap global JS interface from getbootstrap.com docs, and instead you need to set the activeTab prop yourself, or tie into the sapper routing to do same.  
- You also need to do this for the `active` prop on the `NavLink` (not `NavItem` as you have here).
- You also added a `fade` class on the `TabPane` without the `show` class needed to make this visible.


Here is a repl:

https://svelte.dev/repl/e3876beddcd342feb18291d694e16391?version=3.32.2

This simplifies only using on:click, but I think you can use sapper router/routes to determine active state if you need.
Copying code below:

```html
<script>
  import { Nav, NavItem, NavLink, TabContent, TabPane } from 'sveltestrap'; 
  let activeTab = 'sequence';
</script>

<style>
  @import "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css";
</style>

<Nav tabs fill>
  <NavItem >
    <NavLink
      on:click={() => activeTab = 'sequence'}
      active={activeTab == 'sequence'}>
        sequence
      </NavLink>
    </NavItem>
  <NavItem>
    <NavLink
      on:click={() => activeTab = 'deployment'}
      active={activeTab == 'deployment'}>
        deployment
    </NavLink>
  </NavItem>
</Nav>
<TabContent {activeTab}>
  <TabPane tabId="sequence" class="fade show"> 
    <h3>SEQUENCE</h3>
  </TabPane>

  <TabPane tabId="deployment" class="fade show">
    <h3>DEPLOY</h3>
  </TabPane>
</TabContent>```

**Comment by bestguy** [comment]
Let me know if this helps and feel free to close if so.  I agree that the TabContent components need documentation to make this usage clearer.

**Comment by bschwarz** [comment]
Thanks for the quick turnaround, it works now. I am new to Sapper/Svelte, so I am still learning. If I have time this weekend I can help updating docs for this, if needed.
