### ISSUE TITLE
Icons / CSS externally

### ISSUE THREAD

**Issue by michapixel** [bestguy/sveltestrap#236]
Since sveltestrap pulls the icons via css import from jsdeliver:
@import url('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css');

i have two concerns with that: 
a) why don't you omit the version, like in 
https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
which always gives you the latest version 
do you really think this is too risky?

but 
b) is much greater @ least for me/us:
i have privacy concerns with that and cannot build sites with that included.
Do you think it would be possible in any way to use npm "bootstrap-icons" instead? so a local variant?
Maybe just add an option to omit the import statement at install-time so i can always have the latest V. of sveltestrap but must include / import the fonts/svg's myself?

I hope i did make myself clear, it's very early ... ;)

**Comment by bestguy** [comment]
Hi there, yes thanks understood.
This was a MVP to make icons easy basically. The alternatives I see are to:

1. Make the URL configurable or overridable
2. Make people include the external CSS and don't import in this library
3. Make an additional Icon component that does not include styles (without totally confusing people with 2 icon components)
4 Embed the SVG icons directly in this library
5. Make a separate `sveltestrap-icons` library

2 & 3 are related solutions
4 is kind of a hassle without making library huge
My concern with 2 is just the "Icons aren't working" issues, and then people suggesting to support 4 in addition.

Would 1 help if we could do it in a clean way?

**Comment by michapixel** [comment]
The external (local) css won't help since you'd need the fonts too. Plus: the css has likely the "wrong" (unwanted) path to the fonts. 
I would be willing to spend some time with this, although I'm fairly new to svelte and might not have the best view for this kinda decisions.

**Comment by bestguy** [comment]
The CSS uses relative paths to the font files so you can host yourself too I believe.   

I think the alternative is using the svgs directly, but feels like we should start a separate icon package vs combining that many files into sveltestrap bundle

**Comment by bestguy** [comment]
Update on this, I think I'm going to go with option 2 above (Make people include the external CSS and don't import in this library) for next versions of sveltestrap (v4, and v5 for Bootstrap 5).

I don't see any better options given that the version of icons will get stale if I include here.  Thanks for the issue, will update in next week or two.

**Comment by kkarpeev** [comment]
Hello! Can you please hurry with this?

**Comment by bestguy** [comment]
Hi we'll get v4 out soon, but to be honest this Icon component doesn't do much much.  It just outputs a tag with the icon classname:

<i class="bi bi-fonts"></i>

So you can easily use the above with your own icon font in the meantime.

**Comment by bestguy** [comment]
Hi @michapixel, @kkarpeev ,
 
We've published `sveltestrap@4.0.0-beta.1` if you can please try this and confirm it works for you.  You have to directly install the beta version as it's a prerelease:

```bash
npm install sveltestrap@4.0.0-beta.1
```

Please see the instructions here on Icon usage.
https://github.com/bestguy/sveltestrap/tree/v4#note-on-icons

If this works okay we can publish v4 officially.

**Comment by bestguy** [comment]
Will close with release of [v4.0.0](https://github.com/bestguy/sveltestrap/releases/tag/v4.0.0), which removes hard-coded CDN.
Usage documentation for Icon is here: https://github.com/bestguy/sveltestrap#note-on-icons
