### ISSUE TITLE
Input component type=select with different name and value parameters

### ISSUE THREAD

**Issue by romanown** [bestguy/sveltestrap#237]
can I use Input component `type=select` with different name and value parameters? For example, when I select a city, its name is displayed and the value is its ID.
my code is right?
```
<Input type="select" bind:value={a} on:change ={(e) => change(e)}>
<option value = "qqqqqqq">1</option>
	<option value = "wwwwwww">2</option>
	<option value = "zzzzzzz">3</option>
</Input>
```

**Comment by bestguy** [comment]
Hi @romanown ,

Yes that looks correct.  Are you seeing issues with that?

**Comment by romanown** [comment]
i fixed it so far
