### ISSUE TITLE
not show default option after fetch datas

### ISSUE THREAD

**Issue by romanown** [bestguy/sveltestrap#238]
when i fetching the datas for options default value do not match as selected in Input `type = select `component.
if it static so work fine.
but the simple html select works correctly.
[https://svelte.dev/repl/e20365bfaed443a9b2dc66564b4dac4b?version=3.24.0](https://svelte.dev/repl/e20365bfaed443a9b2dc66564b4dac4b?version=3.24.0)

**Comment by bestguy** [comment]
Hi @romanown , it seems to be due to the option value actually being a string.  This works with a small update:

```javascript
let a = "2";
```

https://svelte.dev/repl/0c2998b324e14f53b8afe8e1493369f6?version=3.24.0

Not sure why that would be different from select, but seems reasonable workaround.
