### ISSUE TITLE
firefox: Modal shows too high up on the page

### ISSUE THREAD

**Issue by koo5** [bestguy/sveltestrap#248]
When the page is scrolled down, that is. Even the "backdrop" that you could click on to close the modal is so far up that it's not where the page is scrolled down to, at all. You can find the modal by shift-tab'ing.
currently, this behavior can be seen on https://fullcracy.xyz/  . All you should have to do is to scroll halfway down the page, then click "Participate".

**Comment by bestguy** [comment]
Hi there, thanks, 
I saw issue, but I'm having some trouble duplicating more than once, your site will just scroll to other sections when clicking participate after I reload.
First time, FF moved to the modal+backdrop when I selected it in the inspector, and then it looked fine.

The samples page (https://sveltestrap.js.org/?path=/story/components--modals) works fine with FF, so wondering are you doing something like scrolling page after/during modal open?

**Comment by koo5** [comment]
thanks for looking into it.

 I agree that that the samples page works correctly, even when the iframe (or what is it) is scrolled. 

About my site, it only shows the dialog the first time you click. To get a new dialog, open the profile page (you can do it in another window, it's all localstorage-connected) and click "Log out". This will give you a fresh user and you can click again. 

There indeed is code that causes a scroll after you click, but that can be disabled in settings ("Autoscroll"), and i just commented it out locally to be sure, and it doesn't have any effect.

I also suspected the swiper component i use, but it doesn't seem to have any effect to remove it.

one thing i noticed is, i have `height: 100%;` in `:global(html) {`, and when i remove that, nothing changes visually, but you can actually close the modal by clicking (outside the visible backdrop area)

**Comment by koo5** [comment]
Firefox Nightly currently same behavior.

**Comment by bestguy** [comment]
Yeah that's odd.  One thing is the samples page behaves correctly even when opening a modal in a scrolled page (https://sveltestrap.js.org/?path=/story/components--modals) , and trying to debug your site seems to have some odd visibility with the transform3d attributes?  At least when I mod the values.

I'd rec'd trying to trigger a test modal maybe as part of the layout and not within the the inner components, and see if that narrows the issue to the component CSS or something more global.

**Comment by koo5** [comment]
idk if that's what you call "transform3d", but the problem is this line:
```filter: hue-rotate(var(--hue_rotate)) contrast(var(--contrast)) invert(var(--invert)) saturate(var(--saturate));```

**Comment by bestguy** [comment]
Oh weird, that's all visual/color stuff.  Cool if that fixes!

**Comment by koo5** [comment]
totally does. I put in a hack to unset/set one of the css variables before/after modal.
i'll try to preserve a "do not click this button" demonstration of the faulty behavior in https://fullcracy.xyz/dev_area 
thanks for the help.
