### ISSUE TITLE
Popover add possibility to append to body

### ISSUE THREAD

**Issue by uf0** [bestguy/sveltestrap#254]
It could be useful to add `container:'body'` option. 
For example when attaching a popover to an element inside an `svg` the popover is added but not rendered because it is inside a `svg` tag

**Comment by bestguy** [comment]
Will try and publish this weekend: https://github.com/bestguy/sveltestrap/pull/255

**Comment by bestguy** [comment]
Hi @uf0 ,

We've published sveltestrap@4.0.0-beta.1 that includes this if you can please try this and confirm it works for you. You have to directly install the beta version as it's a prerelease:

```bash
npm install sveltestrap@4.0.0-beta.1
```
If this works okay we can publish v4 officially.

**Comment by uf0** [comment]
Hi @bestguy,

thank you for such quick reply.

I roughly tested it here with `sveltestrap@4.0.0-beta.3`:
https://codesandbox.io/s/v4-gl0sq?file=/App.svelte

It does work by placing the component within the `svg` tag, but the popover doesn't seem to be aligned on the center of the `<circle>` element

I made a second test with `v5` branch (using a work around to place the popover outside the `svg`) and the alignment is fine
https://codesandbox.io/s/v5-qc0wf?file=/App.svelte

So the alignment problem could be linked to and old version of `bootstrap` or ` popper.js`.

**Comment by bestguy** [comment]
Hi @uf0 ,

Thanks for the update.  Yeah that is odd.  Let me see if there's a reason in our code that we can fix, and if not I'll create a new Popover alignment issue and close this one.

**Comment by bestguy** [comment]
Will close with release in [v4.0.0](https://github.com/bestguy/sveltestrap/releases/tag/v4.0.0).

Will create new issue for alignment if can't resolve, thanks for the heads up on these uf0.
