### ISSUE TITLE
Custom CSS on Button

### ISSUE THREAD

**Issue by niraj-gawande** [bestguy/sveltestrap#266]
I want to change the on focus css of the sveltestrap Button component.  How should I target the component? There is no prop to add custom css.

**Comment by bestguy** [comment]
You can pass the style prop, but Svelte also has the `<style>` support.  Can you explain the CSS effect you would like to accomplish?

**Comment by niraj-gawande** [comment]
> 
> 
> You can pass the style prop, but Svelte also has the `<style>` support. Can you explain the CSS effect you would like to accomplish?

I want to change the on focus and and active box-shadow to none.  Not able to target the Button component with class.

**Comment by bestguy** [comment]
Try something like:

```html
<style>
  :global(.btn:focus) {
     /* Your CSS */
   }
</style>
```

**Comment by bestguy** [comment]
If you are trying to do this on just a single button you should be able to use an `#id` selector, etc.   There's no prop we can provide here for this focus use case afaik.

**Comment by niraj-gawande** [comment]
Both the solutions are working.  Thanks 👍
