### ISSUE TITLE
Bootstrap 5 recommendation for Navbar

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#273]
In the Bootstrap 5.0 docs, they recommend always putting a `<div class="container">` inside of Bootstrap's Navbar.

As this could be a regular or fluid container, a few options I can see...

1. Add the `<div class="container">` / `<div class="container-fluid">` to the example in sveltstrap's 5.0 docs recommending that users add it, or...
2. Add a property to the Sveltestrap **Navbar** component like a boolean for **fluid** (defaults to false) and render the `<div class="container">` or `<div class="container-fluid">` within it automatically. This is perhaps the better option given Sveltestrap 5.0 is still in beta and it reduces boilerplate.

**Comment by bestguy** [comment]
Thanks, this sounds like a good idea.  We can address before v5.0.0 (hopefully soon)

**Comment by bestguy** [comment]
Thanks for the heads up, 
Went with a new `container` prop that accepts boolean true (container), false (no container) or 'fluid' (container-fluid, default)
will release with 5.0.0 or 5.0.0-rc.1 soon.

**Comment by bestguy** [comment]
Released with https://github.com/bestguy/sveltestrap/releases/tag/v5.0.0
I'll close this issue but please let me know if you see any problems with the solution.

**Comment by nstuyvesant** [comment]
Confirmed - looking good with Bootstrap 5.0.1
