### ISSUE TITLE
prefix for boostrap class names?

### ISSUE THREAD

**Issue by aktxyz** [bestguy/sveltestrap#290]
I am thinking about using this for a widget thing where widgets can be added to another site with a single <script> tag.

Is there a way to add a prefix to all the bootstrap css classes ? to avoid any collisions with a bootstrap css that may already be included in the page?

**Comment by bestguy** [comment]
Hi, not currently.  You could possibly wrap your widget with an outer class like .your-widget and do some css tricks, or it probably recommend exporting a web component from Svelte compiler.  Your component would need to import it's own Bootstrap css theme though FYI.
