### ISSUE TITLE
Modal fade in is different from in vanilla bootstrap

### ISSUE THREAD

**Issue by john01dav** [bestguy/sveltestrap#291]
In vanilla bootstrap, when a model is opened, as it fades in it slides in from the top of the page. See the live demo on [this](https://getbootstrap.com/docs/4.0/components/modal/) page for an example. But, with Sveltestrap, even with the fade class enabled, the modal simple fades in and does not slide in from the top. In my opinion the fade in looks nicer, so I'd like to report this difference as a bug and/or feature request the slide in being possible — I'm not sure which this is.

**Comment by bestguy** [comment]
Hi, yes you are correct.  Sveltestrap uses built in svelte fade transition, as we are dependent on the intro/outro callbacks to trigger logic.  Bootstrap uses only CSS transitions, and I'm not totally clear on how we can leverage intro/outro with.  But I agree that would be better as some apps/themes to customize the Bootstrap transitions.  I'll take a look now that v5 is out and stable.

**Comment by bestguy** [comment]
Let's keep this issue open as a bug for tracking.

**Comment by bestguy** [comment]
I have a PR (#296) which should fix this, but attempting to update all other transitions as well.
I'll hopefully have these updated within a few weeks.

**Comment by bestguy** [comment]
Hi @john01dav , this should be corrected in #333 
I'll plan to do a release in next few days and you can confirm this works as expected.

**Comment by bestguy** [comment]
Released in [sveltestrap@5.5.0](https://github.com/bestguy/sveltestrap/releases/tag/v5.5.0)
Demo here: https://sveltestrap.js.org/?path=/story/components--modals
Please try out and let me know if you see any issues.
