### ISSUE TITLE
Tooltips on buttons don't show up when button is focused, but do in Vanilla bootstrap

### ISSUE THREAD

**Issue by john01dav** [bestguy/sveltestrap#292]
If I tab through buttons in vanilla bootstrap ([example](https://getbootstrap.com/docs/4.1/components/tooltips/)), the tooltip for the button appears. But, when I do so with Sveltestrap, no tooltip appears ([example](https://sveltestrap.js.org/?path=/story/components--tooltip)). It's also probably worth checking if the screen reader behavior is the same — in some cases, tooltips may provide essential context for those who are visually impaired.

**Comment by bestguy** [comment]
Focus/blur and accessibility should be fixed up by #293 if you'd like to look/review @john01dav 

Thanks for the heads-up on these.

**Comment by bestguy** [comment]
This should be corrected in [5.0.6](https://github.com/bestguy/sveltestrap/releases/tag/v5.0.6)

Please reopen if you see issues.

**Comment by john01dav** [comment]
Thank you very much for such a quick fix! Everything seems to work exactly as it should in 5.0.6
