### ISSUE TITLE
Auto-sizing text areas

### ISSUE THREAD

**Issue by RoryNickolls** [bestguy/sveltestrap#295]
I'm using this component library in a project and want to have a text area that resizes its height automatically as you type. Normally I'd use a function that runs on input / change / window resize and modifies the textarea's height directly.

There doesn't appear to be a way in the Input component to enable this behaviour, nor implement it myself (as the root <textarea> element is not exposed).

If this is within scope of this project, I'd be happy to contribute.

**Comment by bestguy** [comment]
Thanks for the idea.  What would need modification to support this?  Would allowing a way to access/bind the inner element suffice?

**Comment by RoryNickolls** [comment]
@bestguy I've opened a PR demonstrating a way to achieve this, using your suggestion.

**Comment by bestguy** [comment]
Hi @RoryNickolls, this was released in
https://github.com/bestguy/sveltestrap/releases/tag/v5.1.0

Thanks for the issue and PR!  Please comment or reopen if you see issues.
