### ISSUE TITLE
Toast doesn't auto-close after reaching duration

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#299]
Trying to get a **Toast** to fade after 3000 milliseconds. I tried **duration** = 3000 and **duration** = 3 as there's no mention of whether the value is in milliseconds or seconds (Bootstrap uses the [former](https://getbootstrap.com/docs/5.0/components/toasts/#options)). I also tried this attribute `data-bs-delay="3000"` but it didn't work either.

The defaults appear to be set [here](https://github.com/bestguy/sveltestrap/blob/master/src/Toast.svelte#L7).

The Toast stays open indefinitely regardless of the value passed to **duration**.

Environment:
sveltestrap@5.0.6
bootstrap@5.0.1
svelte@3.38.2
@sveltejs/kit@1.0.0-next.110
Browser: Safari 14.1.1 on macOS 11.4

```
<script lang="ts">
  import { Toast, ToastBody, ToastHeader } from 'sveltestrap'
  let isOpen = false
  let duration = 3
  const toggle = () => isOpen = ! isOpen
</script>

<template>
  <button on:click|preventDefault={toggle} type="button" class="btn btn-warning">Get the Newsletter</button>
  <Toast class="position-fixed top-0 end-0 m-3" {duration} {isOpen} fade={true}>
    <ToastHeader {toggle}>Newsletter Subscribed</ToastHeader>
    <ToastBody>You have been successfully subscribed to the newsletter.</ToastBody>
  </Toast>
</template>
```

As an aside: the [examples](https://sveltestrap.js.org/?path=/story/components--toast) have this line:
`<Toast class="me-1" {color}>` which suggests there's a usable color property on the Toast component (but there isn't).

**Comment by bestguy** [comment]
Hi @nstuyvesant 

Ah thanks for the catch.  So we haven't added support for autohide yet.  The 'duration' here is just the fade out transition duration, and not related to autohide.   (Just FYI that the `data-bs-*` attributes do not work with any Sveltestrap components.)

Looks like a useful thing we are missing and easy to add.  I'll look this weekend for the next release, hopefully very soon.

**Comment by bestguy** [comment]
https://github.com/bestguy/sveltestrap/pull/300 if you'd like to review

**Comment by nstuyvesant** [comment]
Thanks @bestguy - will be happy to help test the autohide feature once you get that in place.

**Comment by bestguy** [comment]
Cool thanks, will do a release by tomorrow at latest

**Comment by bestguy** [comment]
Hi @nstuyvesant , this was released in 
https://github.com/bestguy/sveltestrap/releases/tag/v5.1.0

Usage story was added to:
https://sveltestrap.js.org/?path=/story/components--toast

Please try out and close this issue if works out for you

**Comment by nstuyvesant** [comment]
Hi @bestguy - ,

This is working well!
```
  <Toast class="position-fixed top-0 end-0 m-3" autohide={true} delay={4000} duration={800} isOpen={toastOpen}>
    <ToastHeader class="bg-primary text-white" toggle={toastToggle}>Newsletter</ToastHeader>
    <ToastBody class="bg-secondary">You have been successfully subscribed to our newsletter.</ToastBody>
  </Toast>
```
Minor issue In your release notes, you referred to that attribute as **autoHide** vs. **autohide**.

Thanks for implementing this - looking great!

**Comment by bestguy** [comment]
Great, thanks again
