### ISSUE TITLE
export Accordion classes (typescript)

### ISSUE THREAD

**Issue by typhoon51280** [bestguy/sveltestrap#301]
VisualStudioCode can't resolve Accordion and AccordionItem even if it compiles correctly

``
	import { Accordion, AccordionItem, AccordionHeader } from 'sveltestrap';
``

In the file index.d.ts the export of the above classes are missing.

**Comment by bestguy** [comment]
Oops thanks for the catch, should be fixed by #302 
Will do new release soon

**Comment by bestguy** [comment]
Hi this is released in [v5.1.1](https://github.com/bestguy/sveltestrap/releases/tag/v5.1.1) thanks for the issue.
