### ISSUE TITLE
Accordions in index.d.ts are not available.

### ISSUE THREAD

**Issue by pino1068** [bestguy/sveltestrap#304]
Index.d.ts doesn't contain Accordion and related imports. 
VS Code complains in typescript.

Is this maybe done on purpose?

PS: thank you a lot for your work!

**Comment by bestguy** [comment]
Hi @pino1068 ,
This should already be fixed in [v5.1.1](https://github.com/bestguy/sveltestrap/releases/tag/v5.1.1).  Please upgrade if you haven't already, or let me know if you are still seeing issues.
