### ISSUE TITLE
incorrect exported types

### ISSUE THREAD

**Issue by lovasoa** [bestguy/sveltestrap#306]
The following code : 

```svelte
<script lang="ts">
	import {Nav} from 'sveltestrap';

</script>
<Nav navbar class="ms-auto" />
```

raises the following error:

```
Error: Type '{ navbar: true; class: string; }' is not assignable to type 'IntrinsicAttributes & INavProps'.
  Property 'class' does not exist on type 'IntrinsicAttributes & INavProps'. (ts)
```

**Comment by lovasoa** [comment]
The same with Tooltip : 

```svelte
<Tooltip target="xxx">xxx</Tooltip>
```

**Comment by bestguy** [comment]
Hi @lovasoa ,
Can you confirm which Sveltestrap version you are using?  We improved this quite a bit with v5, and haven't back ported to v4 yet.

**Comment by lovasoa** [comment]
Okay, I just updated sveltestrap, but I do still have the error : 

```
		"node_modules/sveltestrap": {
			"version": "5.1.1",
			"resolved": "https://registry.npmjs.org/sveltestrap/-/sveltestrap-5.1.1.tgz",
			"integrity": "sha512-al8ZdC/hx4gbkpGF9vWc6JxpBuDc0Ckj6xC6buly7/fCsxvR4rxAn3mm6/mt6XJYZEXAUZVvmGGPBbTEP4aBLg==",
			"dependencies": {
				"@popperjs/core": "^2.6.0"
			},
			"peerDependencies": {
				"svelte": "^3.29.0"
			}
		},
```

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/552629/121148574-2fc88800-c842-11eb-9a9d-7c449410cd7f.png">

**Comment by bestguy** [comment]
The error you show mentions 'IToastHeader' code removed in older releases: https://github.com/bestguy/sveltestrap/commit/a18695bd3d89c15a98d2df5219594570abde955c#diff-619cc2239a7eb4ef05041767e6ab0e4fb069e98ee9d2c83c2d8e1865c475e141 

I don't think this is a lib issue. Try restarting VS Code and then `npm ci` to clear any cached files.  Please close if that clears.

**Comment by lovasoa** [comment]
Indeed, this fixed the issue. Thank you and sorry for the inconvenience !
