### ISSUE TITLE
warning when building an application

### ISSUE THREAD

**Issue by lovasoa** [bestguy/sveltestrap#307]
when building an application that uses sveltestrap using svelte kit, one gets the following warning : 

```
transforming (163) node_modules/@popperjs/core/dist/esm/modifiers/arrow.js"slide" is imported from external module "svelte/transition" but never used in "node_modules/sveltestrap/src/Alert.svelte", "node_modules/sveltestrap/src/Fade.svelte", "node_modules/sveltestrap/src/Toast.svelte", "node_modules/sveltestrap/src/Collapse.svelte" and "node_modules/sveltestrap/src/Modal.svelte".
```

**Comment by bestguy** [comment]
Hi @lovasoa ,
I'm not seeing an unused `slide` reference.  There is just one usage in Collapse: 
https://github.com/bestguy/sveltestrap/search?q=slide

Can you confirm what version of Sveltestrap you are using?

**Comment by bestguy** [comment]
Thanks, weird, will try a sample out again with Sveltekit

**Comment by lovasoa** [comment]
Thanks ! The warning occurs only during production builds

**Comment by bestguy** [comment]
I am seeing same, but I think it's this Sveltekit issue: 
https://github.com/sveltejs/kit/issues/1299

We do import and use it here: https://github.com/bestguy/sveltestrap/blob/master/src/Collapse.svelte#L63
so seems invalid warning.

**Comment by demetrius-mp** [comment]
@bestguy, i believe this can be closed, just tried building a sveltekit app that uses sveltestrap and i didnt get any errors.

**Comment by bestguy** [comment]
Great, thanks @demetrius-mp !
