### ISSUE TITLE
Modal nodes created outside of Svelte root

### ISSUE THREAD

**Issue by bpiwowar** [bestguy/sveltestrap#308]
In the actual version (5.1.1 and HEAD), modals HTML nodes are created outside of the root element for svelte. In my case, this is a problem since bootstrap CSS is prefixed (using postcss prefixer) to avoid CSS clashes in the interface.
 
Would it be possible to revert to the previous behavior?

**Comment by bestguy** [comment]
Hi @bpiwowar,
You can set the previous behavior with:

```html
<Modal container="inline">
```

Let me know if this doesn't fix your issue.

**Comment by bpiwowar** [comment]
Sorry I should have checked the documentation. 

Yes this works, thanks!
