### ISSUE TITLE
Update and clean up dependencies

### ISSUE THREAD

**Issue by mohe2015** [bestguy/sveltestrap#309]
There are many dependencies with vulnerabilities and also many outdated ones. I think it may be benefical to update them at some point. It should probably be done step by step as I failed to update all at once (which was expected). This is not super important though as most vulerabilities are probably in build-time dependencies.

**Comment by mohe2015** [comment]
I think I will work on this a bit.

**Comment by bestguy** [comment]
https://github.com/bestguy/sveltestrap/releases/tag/v5.1.2

Thanks for the PR, I'll look at updating to webpack 5 and some others with next release of storybook
