### ISSUE TITLE
Override default bootstrap CSS properties

### ISSUE THREAD

**Issue by rouvic** [bestguy/sveltestrap#312]
Hi everyone,
thanks for making such a useful project. I'm wondering if it could be possible to allow overriding of the default bootstrap CSS properties. For instance, I would like to make a wider offcanvas inside a specific svelte component. Something like:
```html
<Offcanvas placement="end">...</Offcanvas>

<style>
.offcanvas-end {
    width: 500px;
}
</style>
```

This code does work as is, because the CSS selector gets renamed by the svelte compiler to `svelte-xxxx` and thus does not override the default attribute anymore.

Maybe another way of doing this would be:

```html
<Offcanvas placement="end" class="wider">...</Offcanvas>

<style>
.wider {
    width: 500px;
}
</style>
```

If this is already doable and I didn't find the right way, I would be glad to know :)

**Comment by bestguy** [comment]
Hi, svelte lets you do global styles such as:

```css
<style>
:global(.offcanvas-end) {
    width: 500px;
}
</style>
```

Otherwise it scopes as you mentioned

**Comment by rouvic** [comment]
Thanks for your answer, I didn't know about this. However, the rule declared with `:global` affects every components, so all the offcanvas in my app are now wider; whilst I would like only the offcanvas inside a specific svelte component to be changed. Any way to do this?
