### ISSUE TITLE
on Modal open, scrollbar remains active

### ISSUE THREAD

**Issue by vfilatov** [bestguy/sveltestrap#317]
I thought modal should hide scrollbar and compensate the width adding "padding-right" to the body element.
It looks to be bug as `5.2.1` does not hide scrollbar but "compensates" the width.

https://svelte.dev/repl/7797d44a3ca74d23aec6a1de5af0c801?version=3.38.3

PS. `<Navbar>` would look better if it extended all the way to the right...

**Comment by vfilatov** [comment]
that behavior might be valid if `scrollable` prop is `false` and `ModalBody` is long enough

**Comment by vfilatov** [comment]
comment out `//conditionallyUpdateScrollbar()` in [src/Modal.svelt](https://github.com/bestguy/sveltestrap/blob/master/src/Modal.svelte#L111) solves my problem

**Comment by bestguy** [comment]
Oh thanks, sorry I've been unable to get to cleaning Modal logic up yet

**Comment by vfilatov** [comment]
Looks to fixed in 5.5.0

**Comment by bestguy** [comment]
Oh great, thank you for letting me know @vfilatov, I assumed the fix for other issue was unrelated.

**Comment by bestguy** [comment]
Will close if resolved, thanks
