### ISSUE TITLE
ListGroupItem on:click not responding

### ISSUE THREAD

**Issue by ieow** [bestguy/sveltestrap#322]
on:click in ListGroupitem is not responding.

here is example in repl
https://svelte.dev/repl/b9dc70579b52428fb866ae77dc846f61?version=3

Am I using it right ?

**Comment by bestguy** [comment]
Hi @ieow ,

Yes this looks like an oversight, we only pass on:click when `tag="button"`, but you shouldn't have to do that.
I can look at fix but temp workaround is by adding `<ListGroupItem tag="button" ...>`:

https://svelte.dev/repl/bcc040a319bf44608172bcddc38b6f59?version=3.38.3

**Comment by bestguy** [comment]
Hi @ieow , this should be fixed in [sveltestrap@5.3.0](https://github.com/bestguy/sveltestrap/releases/tag/v5.3.0) :
https://svelte.dev/repl/359466e990224b53afdf84ce013ebd29?version=3.38.3

**Comment by ieow** [comment]
That was fast.
Thanks for the quick fix !
