### ISSUE TITLE
Static backdrop

### ISSUE THREAD

**Issue by msummers68** [bestguy/sveltestrap#324]
Is there a way to do this with SvelteStrap? https://getbootstrap.com/docs/5.0/components/modal/#static-backdrop -- so that the modal does not close when you press escape or hit a key

Thanks

**Comment by bestguy** [comment]
Not currently but looks like would be simple addition, can look this week!

**Comment by msummers68** [comment]
Thanks so much!

**Comment by bestguy** [comment]
Hi @msummers68 , this was released in [v5.3.1](https://github.com/bestguy/sveltestrap/releases/tag/v5.3.1).

(FYI the "bump" warning animation is missing but will be addressed in #296)
