### ISSUE TITLE
Dark mode and light mode

### ISSUE THREAD

**Issue by shaozi** [bestguy/sveltestrap#335]
Is there a way to switch between dark mode and light mode?

**Comment by bestguy** [comment]
Hi @shaozi , the Bootstrap styles are separate from this library, so you could include a dark theme.
Here is some info: https://github.com/vinorodrigues/bootstrap-dark-5

Nothing in Sveltestrap would need to change/configure to support this

**Comment by bestguy** [comment]
Closing as unrelated to sveltestrap directly
