### ISSUE TITLE
Prevent body from scrolling when a modal is open

### ISSUE THREAD

**Issue by farhat-h** [bestguy/sveltestrap#339]
Hello,

I'm not sure if this counts as an issue but, is there a way to prevent body from scrolling without having to listen for open and close events and [attach a class to the body](https://stackoverflow.com/questions/9538868/prevent-body-from-scrolling-when-a-modal-is-opened) ?

**Comment by bestguy** [comment]
Hi @farhat-h ,
Thanks, this looks broken in v5 - this worked/works correctly in v4 so this is a regression.
Will take a look.

**Comment by bestguy** [comment]
Should be fixed by #340 , will do a release this weekend.  Thanks for the heads up on this

**Comment by bestguy** [comment]
Released in [sveltestrap@5.5.0](https://github.com/bestguy/sveltestrap/releases/tag/v5.5.0)

**Comment by farhat-h** [comment]
Amazing work man
Thank you very much
