### ISSUE TITLE
SvelteStrap 5.5.1 and Bootstrap 5.1.0 - issue with Offcanvas

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#351]
After upgrading Bootstrap from 5.0.2 to 5.1.0 and using the Offcanvas in SvelteStrap 5.5.1, I started to see the gray backdrop overlaid on top of the Offcanvas content. I suspect it's due to this change in Bootstrap 5.1.0:
> Updated modal and offcanvas backdrops to make them unique to each component

I suspect this will be easy to reproduce with [your samples](https://sveltestrap.js.org/?path=/story/components--offcanvas).

**Comment by bestguy** [comment]
Thanks @nstuyvesant , hmm that's annoying they have that breaking change for a minor release.  I'll take a look.

**Comment by bestguy** [comment]
Will leave open until new version is released. Thanks for heads up.

**Comment by nstuyvesant** [comment]
I can confirm sveltestrap@5.6.0 addressed my issue with Offcanvas and bootstrap@5.1.0. Closing this issue.
