### ISSUE TITLE
Uncontrolled Collapse can not work in mobile browser

### ISSUE THREAD

**Issue by miepian** [bestguy/sveltestrap#357]
Uncontrolled Collapse can not work in mobile browser

**Comment by bestguy** [comment]
Hi, this seems to work on mobile for me: https://sveltestrap.js.org/?path=/story/components--collapse

Could you clarify what you are seeing?

**Comment by bestguy** [comment]
Thanks, we can take a look.  To confirm, you only see this in Dev tools? Or do see in actual mobile browser?

**Comment by miepian** [comment]
Yes.issue exists on my Android 9 phone,both Eage,UC browser,QQ browser and wechat,even firefox.

**Comment by bestguy** [comment]
Will release fix today

**Comment by bestguy** [comment]
Hi @miepian , this should be fixed in [sveltestrap@5.6.1](https://github.com/bestguy/sveltestrap/releases/tag/v5.6.1), thanks for the heads up on the issue.
