### ISSUE TITLE
Odd rendering of <Input> in Safari 14.1.2

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#363]
Looking at the samples of the **Input** component on https://sveltestrap.js.org/?path=/story/components--inputs, the rendering of types Date, Datetime, and Time show too much padding especially at the bottom of the Input.

Here's a screenshot on macOS 11.5.2 with Safari 14.1.2 (type="number" shown as well for comparison since it looks good):
![image](https://user-images.githubusercontent.com/5770938/129737355-9f3cf27a-cf07-4a07-ac26-ad24aaf2877e.png)

Here's a screenshot on the same Mac using Chrome 92:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5770938/129737505-860e95ad-6dd1-4101-b226-174d28f93227.png">

Also, you'll notice the color of the date and time separators ("/" and ":") and comma in the placeholder are black while the other content is light gray. This color difference doesn't appear in Chrome (although the placeholders for DateTime, Date, and Time on Chrome are black and don't match the placeholder for type number).

**Comment by bestguy** [comment]
Thanks @nstuyvesant , I think this is a Bootstrap 5.1 CSS issue - am seeing the same on https://getbootstrap.com/docs/5.1/forms/form-control/#example if I change input types to date, etc:

<img width="878" alt="Screen Shot 2021-08-17 at 9 15 07 AM" src="https://user-images.githubusercontent.com/405608/129762984-9e5c64ab-5e74-4d65-8fd6-d34d3930cf0d.png">

**Comment by nstuyvesant** [comment]
Confirmed that Bootstrap@5.1.0 is the culprit. Logged an issue to their repo:
https://github.com/twbs/bootstrap/issues/34760
