### ISSUE TITLE
Unexpected behaviour of Row with multiple columns

### ISSUE THREAD

**Issue by konrad-pawlus** [bestguy/sveltestrap#370]
Hi, I'm using simple Row with 1, 2 or 3 columns depending on size. When used as in [example](https://sveltestrap.js.org/?path=/story/components--layout):

`<Row cols={{ lg: 3, md: 2, sm: 1 }}>`

and screen is smaller than "sm" multiple columns appear.

Replacing above definition with workaround:

`<Row cols={{ xl: 3, lg: 3, md: 2, sm: 1, xs: 1 }}>`

solves this problem.

In my understanding expected behaviour would be that it would be enough to define Row as in example. Replacing this with pure Bootstrap CSS seams to work as expected.

**Comment by bestguy** [comment]
Hi @konrad-pawlus ,

Thanks, would you mind making a repl that shows the incorrect behavior?
https://svelte.dev/repl/8ed6d1663e42490ea57b005cc12651f5?version=3.42.4

I want to make sure I understand the issue.

**Comment by konrad-pawlus** [comment]
Hi @bestguy , I created reply: https://svelte.dev/repl/8ed6d1663e42490ea57b005cc12651f5?version=3.42.4
Please select any value from first select box, than do this once more, what I observe:

- select Cat 2 - still null value is bound,
- Select Cat 3 - value of 2 is bound,

Than do same with regular select. It works as expected.

**Comment by konrad-pawlus** [comment]
Reply created: https://svelte.dev/repl/cc57e64d65ff4831b3dc66f8325bdeb1?version=3.42.4

Result when resized:
![image](https://user-images.githubusercontent.com/84272230/132165881-61af709e-249c-46f9-924d-875816bde9be.png)

**Comment by bestguy** [comment]
Great thanks, will take a look

**Comment by bestguy** [comment]
So after looking this @konrad-pawlus , I'm wondering what criteria defines the correct/incorrect in your example.

My understanding of https://getbootstrap.com/docs/5.1/layout/grid/#row-columns is that if no breakpoints are used, then the col count will be consistent across all breakpoints.  E.g. `<Row cols={3}>`. If no col size or breakpoints the column count will be whatever number of cols passed to the row.

If breakpoints are specified, the Bootstrap CSS behavior is for that breakpoint and above.  For breakpoints not specified, the column count will be whatever number of cols passed to the row.  

So in your "incorrect" example `<Row cols={{ lg: 3, md: 2, sm: 1 }}>` it seems expected `xs` breakpoint will show the 5 cols.

Does this make sense?

**Comment by konrad-pawlus** [comment]
My understanding was that this should behave exactly like Bootstrap, which is shown on second grid example in reply. 

This is using **min-width** in Bootstrap _("We most commonly use min-width in our media queries", https://getbootstrap.com/docs/5.1/layout/breakpoints/ )_ so second pure Bootstrap grid behaves as I would expect.

**Comment by konrad-pawlus** [comment]
I analyzed once more your explanation and how Bootstrap works and  I think I misinterpreted how you map those cols parameters. Seams you ar right it works as  it should. Thank you!
