### ISSUE TITLE
Error when evaluating SSR module /node_modules/sveltestrap/src/Dropdown.svelte (and others)

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#373]
Have been upgrading SvelteKit as new versions come out (now on 1.0.0-next.162).

Starting to see a few errors that may be related to new versions of vite bundled with it. Vite seems to be getting pickier about subordinate packages. I had to do a workaround for @carbon/telemetry as well.

> 4:32:13 PM [vite] Error when evaluating SSR module /node_modules/sveltestrap/src/Dropdown.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /node_modules/sveltestrap/src/ButtonDropdown.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /node_modules/sveltestrap/src/index.js?v=a77b9f19:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /src/lib/Menus.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /src/lib/Carousel/index.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /src/lib/Header.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> 4:32:13 PM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> Missing "./dist/esm/popper" export in "@popperjs/core" package
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)
> Missing "./dist/esm/popper" export in "@popperjs/core" package
> Error: Missing "./dist/esm/popper" export in "@popperjs/core" package
>     at bail (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43177:8)
>     at resolve$1 (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43253:10)
>     at resolveExports (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43751:12)
>     at resolveDeepImport (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43768:26)
>     at tryNodeResolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43510:11)
>     at Context.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:43373:28)
>     at Object.resolveId (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50342:55)
>     at async TransformContext.resolve (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:50143:23)
>     at async normalizeUrl (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75774:34)
>     at async TransformContext.transform (/Users/nates/dev/shy-svelte/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75909:57)

**Comment by bestguy** [comment]
Hi @nstuyvesant , thanks for the heads up.

This popper stuff is a real pain in the ass... their use of node.process in the main export does not work in svelte.repl or sapper, and the esm one doesn't work in SvelteKit...

Let me see if we can do our own fork of popper or something.

**Comment by nstuyvesant** [comment]
I was running an experiment to see what would happen if all dependencies are brought up to current versions...
```bash
$ rm -rf node_modules package-lock.json .svelte-kit
$ npm install
$ npm run dev -- --host --open
```

After comparing what changed in my package-lock.json, looks like the issue is @popperjs/core getting upgraded to 2.10.0.

bootstrap@5.1.0's package.json uses `^2.9.3` and sveltstrap@5.6.2 `^2.9.2` for @popperjs/core.

Perhaps both would be better with `~2.9.3` for now given this change:
https://github.com/popperjs/popper-core/pull/1342

**Comment by nstuyvesant** [comment]
Looks like there was a @popperjs/core release last night that reverted the exports:
https://github.com/popperjs/popper-core/pull/1362

**Comment by bestguy** [comment]
Thanks @nstuyvesant  for the info.  Sorry am trying to catch up - should we pin to particular version of popper to avoid this?

**Comment by nstuyvesant** [comment]
Should I close this here as it's not a sveltestrap issue per se or would you want to adjust this package's dependency?

Pinning to `~2.10.1` would probably be good as long as all your tests pass against it.

**Comment by benmccann** [comment]
There's no need to pin. Anyone who installs now will get the latest working version

**Comment by bestguy** [comment]
Weird as I'd have assumed them adding export maps would have helped the original issue 😅.

**Comment by bestguy** [comment]
Thanks all for the help.
