### ISSUE TITLE
Warning: <Toast> was created without expected prop "header"

### ISSUE THREAD

**Issue by nstuyvesant** [bestguy/sveltestrap#376]
I'm using ToastHeader instead of the Toast **header** property. My console displays...
> <Toast> was created without expected prop "header"

Minor thing but I think if you change [this line](https://github.com/bestguy/sveltestrap/blob/master/src/Toast.svelte#L17) from
```
 export let header;
```
to
```
 export let header = undefined;
```
the warning should go away. Your property, **header**, is not required according to [Toast.d.ts](https://github.com/bestguy/sveltestrap/blob/master/src/Toast.d.ts).

Just an annoying Svelte warning.

**Comment by bestguy** [comment]
Ah thanks for the catch, will do 👍

**Comment by bestguy** [comment]
Released in [sveltestrap@5.6.3](https://github.com/bestguy/sveltestrap/releases/tag/v5.6.3), thanks for the issue.
