### ISSUE TITLE
Sveltestrap desn't work with SvelteKit (latest)

### ISSUE THREAD

**Issue by Swoopy** [bestguy/sveltestrap#385]
When using Sveltestrap components Sveltekit always give SSR/Static build errors. See attached pictures.

![sveltestrap_ssr](https://user-images.githubusercontent.com/2881012/133121382-9dbb71e4-2f99-40cf-8d73-7593a245b38a.png)
![sveltestrap_static](https://user-images.githubusercontent.com/2881012/133121383-9fdf1652-2731-4519-93c3-bae2c28d353e.png)

**Comment by bestguy** [comment]
Is this a dupe of https://github.com/bestguy/sveltestrap/issues/373?

How are you importing the components?  Also which version of popper.js do you have installed?

**Comment by Swoopy** [comment]
Yes, it seems to be the same problem as #373 .

The components are imported as fallows:
`import {
		Dropdown,
		DropdownItem,
		DropdownMenu,
		DropdownToggle
	} from 'sveltestrap/src';`

Popper.js is version 2.10.1.

I've already tried to put the packages under devDependencies, but it didn't work.

**Comment by bestguy** [comment]
Thanks, could you please try importing like:

```javascript
import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle } from 'sveltestrap';
```

as perhaps the SSR docs no longer apply to sveltekit

**Comment by Swoopy** [comment]
No. It seems it was my mistake. Sorry about it! Popper was installed independently too and that was the problem. :(
