### ISSUE TITLE
Typescript: ollapse should be Collapse

### ISSUE THREAD

**Issue by pappasam** [bestguy/sveltestrap#394]
https://github.com/bestguy/sveltestrap/blob/3d8ae637492ad13335d89fb604d3a825be608edb/src/Collapse.d.ts#L15

Although I'm not certain, my guess is that the mispelled `ollapse` here may be responsible for the following seemingly spurious type error:

![image](https://user-images.githubusercontent.com/3723671/136122228-e41c042e-1d52-4e19-8310-b3286923ca49.png)

**Comment by bestguy** [comment]
Ah thank you!  Let me try and fix this weekend.

**Comment by bestguy** [comment]
Released in https://github.com/bestguy/sveltestrap/releases/tag/v5.8.1
Thanks for the heads up
