### ISSUE TITLE
Tooltip with ref to DomElement instead of id

### ISSUE THREAD

**Issue by kaipaysen** [bestguy/sveltestrap#395]
I'm using the Tooltip within a svelte component which might be used multiple times. 
Providing `id`s for the "to be tooltiped" element does not work properly in this case.

I've provided an example here:
https://svelte.dev/repl/36c3675121fa40c6a1407a50765b7b8d?version=3.42.6

Can we get a Tooltip `target` property which accepts a dom ref as an alternative to an id?

**Comment by bestguy** [comment]
Thanks @kaipaysen , this is released in [v5.7.0](https://github.com/bestguy/sveltestrap/releases/tag/v5.7.0)
