### ISSUE TITLE
How to change the color theme?

### ISSUE THREAD

**Issue by ajerni** [bestguy/sveltestrap#397]
How can we change the color theme? For example for the Button components color="primary" property?

**Comment by bestguy** [comment]
The goal of this library is to use Bootstrap CSS/themes defined or hosted externally.   For example you can link to stylesheets such as: https://www.bootstrapcdn.com/bootswatch/
Or use your own company's Bootstrap theme.

I realize this might seem inconvenient, but theming and styling support is not within the scope of this project, thanks.
