### ISSUE TITLE
<ToolTip/> throws HTMLElement is not defined

### ISSUE THREAD

**Issue by lovasoa** [bestguy/sveltestrap#414]
Hello,
  It looks like since the latest update the `<ToolTip/>` element is broken and throws `HTMLElement is not defined` when server-side rendered.

Initially reported in https://github.com/lovasoa/sanipasse/issues/145

**Comment by kaipaysen** [comment]
Hi lovasoa,

this might be related to the [`Tooltip` property `target`](https://github.com/bestguy/sveltestrap/blob/master/src/Tooltip.d.ts#L12). 
I'll try to reproduce the issue on my side.  You might want to try to pass an empty String as a target in the meantime.

Kai

**Comment by lovasoa** [comment]
No, it always throws an error, even if all properties are defined correctly. The component tries to reference objects that are not defined during server-side rendering.

**Comment by kaipaysen** [comment]
Acording to https://svelte.dev/blog/whats-new-in-svelte-september-2021 HTMLElement is supported starting from svelte 3.42.2. Sveltestrap uses [3.38.2](https://github.com/bestguy/sveltestrap/blob/master/package.json#L87). Would upgrading svelte solve the issue?

**Comment by lovasoa** [comment]
The changelog may be a little confusing. It adds HTMLElement as a known global during compilation so as not to trigger errors. But is doesn't actually define it, it expects it to be defined by the browser. In SvelteKit, components can be rendered on the server side, where HTMLElement is not defined.

**Comment by kaipaysen** [comment]
Some days ago I reproduced the issue with an older svelte kit application. Just some minutes ago I tried to reproduce the issue with an uptodate svelte kit application (sveltekit next227, svelte 3.46.1) and the issue has vanished. Would you mind doublechecking on your side?

**Comment by lovasoa** [comment]
Yes, I can confirm the bug is present with the latest sveltekit. The bug is going to be present as long as sveltestrap tries to reference undefined variables on the server side. The bug is in this repo, not in sveltekit. I was introduced in https://github.com/bestguy/sveltestrap/pull/396

**Comment by lovasoa** [comment]
Here is a simple reproduction you can paste into a default sveltekit project

```svelte
<script>
	import { Tooltip } from 'sveltestrap'
</script>

<Tooltip target='xxx'>bug</Tooltip>
<h1 id='xxx'>hello</h1>
```

**Comment by bestguy** [comment]
Thanks for the fix, will release this weekend.

**Comment by bestguy** [comment]
Released in: https://github.com/bestguy/sveltestrap/releases/tag/v5.8.0
