### ISSUE TITLE
Property 'group' does not exist on type definition of `InputProps`

### ISSUE THREAD

**Issue by mopeneko** [bestguy/sveltestrap#415]
When I use `group` property of Input, TypeScript says:

> Type '{ type: "radio"; group: number; value: string; label: string; }' is not assignable to type 'IntrinsicAttributes & InputProps'.
  Property 'group' does not exist on type 'IntrinsicAttributes & InputProps'.

code:

```html
<Input type="radio" bind:group={a} value="0" label="a" />
```

The reason is that `group` property is not included in the type definition.

https://github.com/bestguy/sveltestrap/blob/096bfb3dbae03cd9665248866222a57229b3b3ad/src/Input.d.ts#L29-L41

**Comment by bestguy** [comment]
Thanks, will release this weekend

**Comment by bestguy** [comment]
Released in: https://github.com/bestguy/sveltestrap/releases/tag/v5.8.0
