### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by mishankov** [bestguy/sveltestrap#431]
Probably after latest release https://github.com/bestguy/sveltestrap/releases/tag/v5.8.1
Chrome 97.0.4692.71 and Firefox

![изображение](https://user-images.githubusercontent.com/27302114/150677608-32ae762f-d4cf-4d9b-829f-0ebd5fdd194e.png)

**Comment by MetaMmodern** [comment]
same for me( webarcive giving empty pages for this website(

**Comment by bestguy** [comment]
Oops thanks, let me see what's up, may have been audit updates.

**Comment by bestguy** [comment]
Thanks @mishankov for the heads up, corrected by #433   
Was some storybook dependency issue...
