### ISSUE TITLE
Feat: Support horizontal collapse

### ISSUE THREAD

**Issue by demetrius-mp** [bestguy/sveltestrap#444]
i was trying to rebuild [this sidebar](https://www.codeply.com/p/LXYndDByBf) using sveltestrap, but the default animations works only vertically, which feels weird for this use case. I tried adding `.collapse-horizontal` to the `Collapse` component, but it happened to be even weirder.

**Comment by bestguy** [comment]
Thanks, yeah I attempted adding support and was a little confused on how this was supposed to work.  Happy to take a look again and either PR or add my notes here if someone could pick it up.

**Comment by bestguy** [comment]
I think this is straightforward if you'd like to review @demetrius-mp : https://github.com/bestguy/sveltestrap/pull/445/files

**Comment by bestguy** [comment]
Released in [v5.9.0](https://github.com/bestguy/sveltestrap/releases/tag/v5.9.0), thanks for the heads up.
