### ISSUE TITLE
adding card component breaks sapper nav

### ISSUE THREAD

**Issue by shedali** [bestguy/sveltestrap#46]
- install sapper template `npx degit "sveltejs/sapper-template#rollup myapp`
- install sveltestrap, include css from cdn
- include card component
```<script
import { Card, CardBody } from "sveltestrap";
</script>
```

The component renders, but when I change tabs, I get the following console error:

```
sveltestrap.es.js:1 Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at os (sveltestrap.es.js:1)
    at Object.o (sveltestrap.es.js:1)
    at transition_out (index.mjs:672)
    at Object.outro [as o] (sveltestrap.es.js:1)
    at transition_out (index.mjs:672)
    at Object.update [as p] (App.svelte:22)
    at Object.update [as p] (App.svelte:19)
    at Object.update [as p] (_layout.svelte:18)
    at update (index.mjs:619)
    at flush (index.mjs:593)
```

repro at https://codesandbox.io/s/7synm

**Comment by bestguy** [comment]
Hmm, this is odd, thanks for the heads-up.
It's actually any component, not just Card.
I haven't used Sapper but do you know where the transitions are being applied?  I see 
transition_out, and outro mentioned but don't see any transitions in the code or when changing pages.

**Comment by shedali** [comment]
I'm also new to Sapper; will let you know if I get any more info

**Comment by bestguy** [comment]
Hi @shedali , I've published a beta version for another which might correct your issue. 

Can you please try `npm install sveltestrap@3.1.2-0` and confirm?

**Comment by bestguy** [comment]
Hi again @shedali , I tested this in sapper, and looks like #50 will resolve this.
Before it's merged, you should be able to use this prerelease:

`npm install -D sveltestrap@3.1.2-0`

(-D is important to add it to dev dependencies, as explained here: https://github.com/sveltejs/sapper-template#using-external-components)

**Comment by shedali** [comment]
that works thanks @bestguy

**Comment by bestguy** [comment]
Cool, I'll plan on merging and publishing 3.2 in the next few days.  I'll close this issue at that time.

**Comment by bestguy** [comment]
Fixed in https://github.com/bestguy/sveltestrap/releases/tag/v3.2.0
