### ISSUE TITLE
sveltestrap / svelte-routing problem

### ISSUE THREAD

**Issue by LaughingBubba** [bestguy/sveltestrap#49]
# Problem

```svltestrap``` components don't want to play nicely with ```svelte-routing``` navigate function.

When implementating a scenario like:
```javascript 
on:click={() => navigate("/some-url")}
``` 
the script crashes with opaque message like:
```bash
19:55:56.734 TypeError: os is undefined sveltestrap.es.js:1:392
```

I've made a repo that replicates the problem here: https://github.com/LaughingBubba/sveltestrap-problem

PS: Luv your work!

**Comment by bestguy** [comment]
Thanks @LaughingBubba , will take a look.  This maybe related or similar to #46

**Comment by bestguy** [comment]
Hi @LaughingBubba , I believe this will be fixed with #50 

If you'd like to try out, please use the pre release here:
`npm install sveltestrap@3.1.2-0`

I tested on on your problem repo (thank you for doing that) and seems to resolve.  After merge, will likely publish as 3.2

**Comment by LaughingBubba** [comment]
W00t! It works. Thanks. Sooo ... how far off is 3.2 from being published?

**Comment by bestguy** [comment]
Done!  https://github.com/bestguy/sveltestrap/releases/tag/v3.2.0

Thanks for the heads-up.  Will close, let me know if you see any issues.
