### ISSUE TITLE
Problem Modal Cannot read property 'c' of undefined

### ISSUE THREAD

**Issue by victorhcortesp** [bestguy/sveltestrap#51]
this error happens when you want to close the modal

Error:
`index.mjs:676 Uncaught (in promise) TypeError: Cannot read property 'c' of undefined`

```"devDependencies": {
    "npm-run-all": "^4.1.5",
    "rollup": "^1.12.0",
    "rollup-plugin-commonjs": "^10.0.0",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^4.0.4",
    "svelte": "^3.12.1"
  },
  "dependencies": {
    "sirv-cli": "^0.4.4",
    "sveltestrap": "^3.1.1"
  }

**Comment by bestguy** [comment]
Hi @victorhcortesp , there seems to be a problem with some builds with sapper, SSR, etc.

Can you please try `npm install -D sveltestrap@3.1.2-0` and let me know if resolves?
This is a pre-release version for #50 PR.

**Comment by bestguy** [comment]
I've published v3.2 (https://github.com/bestguy/sveltestrap/releases/tag/v3.2.0) if you can try out and confirm corrects your issue

**Comment by victorhcortesp** [comment]
Try version 3.2 and solve the problem, but I am seeing some alerts in the console

Here is the example where I am using it
https://github.com/victorhcortes/intro_svelte/tree/implement_sveltestrap


![image](https://user-images.githubusercontent.com/38927248/65430720-f8037d80-dddd-11e9-9cc5-f1ac733ca146.png)

**Comment by bestguy** [comment]
Thanks @victorhcortesp, 
Those alerts sounds unrelated, but can you post your sample code here or in a gist?

**Comment by victorhcortesp** [comment]
code where you implemented the modal component

```
<script>
  import { createEventDispatcher } from "svelte";
  import {
    Button,
    Modal,
    ModalBody,
    ModalFooter,
    ModalHeader
  } from "sveltestrap";

  const dispatch = createEventDispatcher();
  const closeModal = () => dispatch("closemodal");
</script>

<Modal isOpen>
  <ModalHeader toggle={closeModal}>
    <slot name="header" />
  </ModalHeader>

  <ModalBody>
    <slot />
  </ModalBody>

  <ModalFooter>
    <Button color="primary" on:click={closeModal}>Close</Button>
  </ModalFooter>
</Modal>

**Comment by bestguy** [comment]
Thanks @victorhcortesp , looks like a different issue, we need to make sure props are initialized with `undefined` to avoid this.   I created a new issue (#54) and will close this one.
