### ISSUE TITLE
Error: Argument of type 'typeof ModalHeader' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'

### ISSUE THREAD

**Issue by JandosKh** [bestguy/sveltestrap#510]
I'm using VS Code 1.72 with extension for Svelte v106.2.0. With Sveltekit rc1 and typescript, I have a lot of errors like below:
Argument of type 'typeof ModalHeader' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
Sample code:
```
<Modal isOpen={showDialog} toggle={toggleDialog} class="mt-5">
	<ModalHeader toggle={toggleDialog}>{t('Company deletion')}</ModalHeader>
	<ModalBody class="font-sm">
		{t('The company will be deleted. Continue?')}
	</ModalBody>
	<ModalFooter>
		<Button class="btn-sm" color="primary" on:click={async () => await deleteCompany()}>{t('Yes')}</Button>
		<Button class="btn-sm" color="secondary" on:click={toggleDialog}>{t('No')}</Button>
	</ModalFooter>
</Modal>
```

This happened when I upgraded from sveltestrap v5.7.0 to v5.9.0.
The code actually runs without an issue, but VS Code shows the above errors. What am I missing?

**Comment by bxgrant** [comment]
I am seeing the same

**Comment by onos9** [comment]
I'm also seeing the same after upgrading, is this a bug?

**Comment by bxgrant** [comment]
Any word on this?  It makes it super hard to code with errors everywhere.

**Comment by bxgrant** [comment]
Any word on this?  I'm all in on this thing but man I need help on this.  Anyone out there?  Ideas?

**Comment by bxgrant** [comment]
Upgraded to the latest versions of everything and seemed to go away.

**Comment by JandosKh** [comment]
Looks like, the new version solved this issue. Closing.
