### ISSUE TITLE
Sveltekit compatibility

### ISSUE THREAD

**Issue by bestguy** [bestguy/sveltestrap#517]
Now that Sveltekit is release candidate and _should_ be mostly stable, we'll aim to ensure compatibility with it as soon as possible.

I appreciate the excitement around Sveltekit and know some of you are using in production - but our experience in past with Sapper (and similar with Sveltekit beta so far) is that things would change quite a bit in the beta period, and was difficult to chase after every change.

The two main issues appear to be:
1. Dependency on PopperJS, which has some (annoying) issues around it's use of `process.env`
2. Some components were not designed for SSR environments and need to more defensive about `window` usage, etc.

I am also _unwilling to compromise usage in svelte.dev/repl_ which I and other use heavily, so suggestions or PRs that will only work in Sveltekit won't be considered, which has been the cause of some of the delays as well.

We have added an additional maintainer to project which should help with updates.  Thanks again for using this library and your patience given it's not a commercial or sponsored project.

**Comment by bato3** [comment]
Do I understand correctly that an acceptable proposal is one that works with Repl and SK?

Should sveltestrap work in any other environments?

**Comment by hakimzulkufli** [comment]
> Should sveltestrap work in any other environments?

As a user of this project, yes. Too many Svelte projects I see moved over to working only on SvelteKit exclusively. I also use Svelte on other things without SvelteKit.

**Comment by carlyg7** [comment]
Dependencia de PopperJS, que tiene algunos problemas (molestos) en torno al uso deprocess.env

como se soluciona esto?
