### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by bestguy** [bestguy/sveltestrap#579]
Hi all,

I'd like to reach out to the community and ask if any of you (or your company) would like to be primary maintainers of Sveltestrap.

I still care about this project :heart:, however I have not had the time I expected in past year to work on this project (or Svelte), apologies for the long delays.  My latest role was supposed to include dedicated time for this open source work, but that did not happen unfortunately.  With the upcoming Svelte 5 changes, I'm probably not the best steward for the project going forward given I'm not using Svelte professionally.

I can set up a sveltestrap organization and remain as a secondary maintainer or reviewer if that would help.   I am also happy to meet/onboard new maintainers and available for questions.  However, I unfortunately don't have time to be mentor for junior devs or students, and would ask that you have Svelte experience already.

Please leave a comment here if interested, or feel free to message/connect on LinkedIn: https://www.linkedin.com/in/gthomas/

:heart: bestguy

P.S. alternately, if your company is hiring for a React or Svelte role that could include 10-15% time for working this project, would love to chat.

**Comment by RoryDuncan** [comment]
Thanks for your stewardship and the amount of effort you've put in thus far, @bestguy.

Would sponsorship alleviate the maintenance situation? Sometimes it's easier for organizations to allocate funds than it is to allocate time. Thought I'd raise that in case it makes different realities possible.

Either way—I'm sure it may take some time for individuals to have conversations with their managers and orgs to determine what amount of help is possible.

**Comment by bestguy** [comment]
Thanks @RoryDuncan , I had considered sponsors, but think in my case time is probably bigger factor, and want to make sure I'm actually available before I took that step.  Will give it some thought, thanks.

**Comment by bestguy** [comment]
**Update**: a business sponsor has stepped up with time and developer help. ❤️   We'll be moving Sveltestrap to an organization, and will do an official new major release for Svelte 4+ with this new org and namespace.  

Will update soon on docs, any repo changes, and further details.  Thanks all for your help and using Sveltestrap.  
Have a merry Christmas, and happy new year 🎄

**Comment by bestguy** [comment]
Many thanks to [Opensense](https://www.opensense.com) and @dysfunc for this sponsorship!
