### ISSUE TITLE
[Navbar] Collapse elements not visible when area is big enough

### ISSUE THREAD

**Issue by RaulVS14** [bestguy/sveltestrap#59]
Collapse elements should remain visible in desktop and only disappear into togglable mode when the screen isn't wide enough
Current state (collapse element link are not visible)
![image](https://user-images.githubusercontent.com/8948348/65820805-24802500-e236-11e9-8e78-855dfa26db78.png)

Expected( currently only achieved using the toggle in mobile view and then it's possible to see them in desktop):
![image](https://user-images.githubusercontent.com/8948348/65820782-d834e500-e235-11e9-828d-fe211443277a.png)

**Comment by bestguy** [comment]
Hi @RaulVS14 , we just released [v3.2.2](https://github.com/bestguy/sveltestrap/releases/tag/v3.2.2) this morning, which fixes a related issue.  Can you please try v3.2.2 and confirm if you still see this issue?

**Comment by bestguy** [comment]
Hi @RaulVS14 actually this should be fixed in [sveltestrap 3.2.3] (https://github.com/bestguy/sveltestrap/releases/tag/v3.2.3), thanks for the heads up.
Please confirm your issue is corrected and can close the issue.

**Comment by RaulVS14** [comment]
Yes, issue is corrected. I had an problem with using it in my environment though. It gave me `window is not defined` error. The problem occurred from Collapse for windowWidth. I managed to get it working by wrapping it in the onMount method. I also defined windowWith variable outside the method onMount, because svelte:window couldn't find it.

**Comment by bestguy** [comment]
Hi Raul, hmm, that's weird.  It this a normal app or SSR?

**Comment by RaulVS14** [comment]
I am not sure, I've seen SSR errors, so I guess it's SSR. 
My current setup:
I started with sapper template running in local with npm dev run. To this I added sveltetrap for bootstrap functionality.

**Comment by bestguy** [comment]
Thanks, I'll test with Sapper.  
FYI in SSR environments you may need to import the component src directly:

`import Card from 'sveltestrap/src/Card.svelte';`

but am still trying to determine the 'correct' way for Svelte 3, has been a lot of changes.

**Comment by RaulVS14** [comment]
Yes, thank you! I changed the import, when I got SSR errors.
