### ISSUE TITLE
No bind on switch

### ISSUE THREAD

**Issue by hmmhmmhm** [bestguy/sveltestrap#61]
```html
<CustomInput
     type="switch"
     id="blabla"
     checked={isAllowedNotification}
     disabled
/>
```

it works but, can't be use `bind:checked`.

**Comment by bestguy** [comment]
Thanks for the heads-up, will correct this week.

**Comment by bestguy** [comment]
Actually `<Input type="checkbox" bind:checked />` has same issue.. will correct at same time

**Comment by bestguy** [comment]
Hi @hmmhmmhm ,
This should be corrected in version [3.2.5](https://github.com/bestguy/sveltestrap/releases/tag/v3.2.5)


Can you please confirm and we can close the issue.

**Comment by hmmhmmhm** [comment]
Perfect

**Comment by arthurgermano** [comment]
Hii... Is it still happening?

Because I am trying to bind to checkbox and nothing...
No events, no bind.. nothing.. 

=(
