### ISSUE TITLE
Question - using https://themes.getbootstrap.com

### ISSUE THREAD

**Issue by lasergoat** [bestguy/sveltestrap#70]
Hello, I want to use Bootstrap with a new Svelte project I'm working on - but I'd like to use a theme from https://themes.getbootstrap.com or even something like this: https://demos.creative-tim.com/argon-design-system/index.html

is it possible to use these themes with Svelte or sveltestrap?

**Comment by bestguy** [comment]
Hi @lasergoat , yes you can use themes.  The easiest way is to include the Bootstrap theme in your layout head tag:

```html
<head>
  <link rel="stylesheet" href="https://demos.creative-tim.com/argon-design-system/assets/css/argon.min.css">
</head>```

or in your app using svelte:head:

```html
<svelte:head>
 <link rel="stylesheet" href="https://demos.creative-tim.com/argon-design-system/assets/css/argon.min.css">
</svelte:head>
```

<img width="597" alt="Screen Shot 2019-10-19 at 1 05 00 PM" src="https://user-images.githubusercontent.com/405608/67150839-a4b40c00-f271-11e9-866b-5b3c601596e9.png">

**Comment by bestguy** [comment]
Closing as answered, please reopen if not resolved @lasergoat

**Comment by lasergoat** [comment]
@bestguy Thank you. I ended up using Bulma which doesn't have it's own js, it's scss only so I didn't have to figure out how to handle all the custom vanilla js code that came with the other themes I'd been considering. The main drawback is now I've just had to be building my own theme from scratch
