### ISSUE TITLE
Nested async components error when switching components

### ISSUE THREAD

**Issue by telemmaite** [bestguy/sveltestrap#71]
Hello, please take a look at the following two comments.
https://github.com/sveltejs/svelte/issues/3448#issuecomment-530331354
https://github.com/sveltejs/svelte/issues/3448#issuecomment-541386356

I think as mentioned here:

> In the end @halfnelson came up with a solution where the pre-built component should declare at least the svelte/internal imports as globals (rollup) or externals (webpack).
You can see that comment and my comment afterwards stating what I did here: #3671 (comment)
If this is the problem that's being discussed here then **_it would seem that projects distributing pre-built Svelte components should set their bundles to be built expecting at least the svelte/internal import to be provided as a global somewhere_**.

I guess that sveltestrap case is to expect global svelte/internal import `npm install --save svelte sveltestrap`.

**Comment by bestguy** [comment]
Thanks for the heads up @telemmaite 
We've had a lot of trouble know what the 'official' support for pre-bundled components are - 
there's been SSR issues, suggestions to add svelte source files to bundle, etc.
Svelte 3 seems like a work in progress in this area compared to Svelte 1-2...

I'll see what we can do to improve this, thanks for the issue links
