### ISSUE TITLE
Page JS weight

### ISSUE THREAD

**Issue by nkev** [bestguy/sveltestrap#76]
Svelte newby here, so please forgive me if this seems like a silly question. 
Isn't Svelte supposed to **reduce** the overall page weight? I'm seeing the sveltestrap page JS weight is many times the size of jQuery/Bootstrap 4 version. What am I missing?

**Comment by bestguy** [comment]
Mind sharing a repo or sample?  Webpack, Rollup, etc?
Svelte is designed to compile away any frameworks down to vanilla JS.
However Svelte 3 is a big change and app developers or this lib might be missing something.

**Comment by nkev** [comment]
Sure. I'm just talking about the size of the JS payload in the browser:

![image](https://user-images.githubusercontent.com/5410916/67729757-70e19f00-fa46-11e9-9051-0054f2e1c137.png)

versus:

![image](https://user-images.githubusercontent.com/5410916/67729764-76d78000-fa46-11e9-90b1-d6572774040f.png)

**Comment by bestguy** [comment]
I see, if you are comparing the Storybook docs, that is a different beast! - I think storybookjs is internally using React and other libraries, not Svelte.  (The stories are written in Svelte though)

Here is a Hello World app using [Sapper](https://sapper.svelte.dev) and Sveltestrap:

<img width="670" alt="Screen Shot 2019-10-28 at 8 09 41 PM" src="https://user-images.githubusercontent.com/405608/67734702-f6217100-f9be-11e9-8474-f546f8c68244.png">

You can see this is much smaller (14kb!)

**Comment by bestguy** [comment]
Try out the Svelte quick start (https://svelte.dev/blog/the-easiest-way-to-get-started) or  [Sapper](https://sapper.svelte.dev/) for more power.  Both should demonstrate small code sizes. 

Will close but feel free to reopen if you see a size issue with this lib.

**Comment by nkev** [comment]
I see. Thanks for that. So to be clear, in my Sveltestrap screenshot above, which JS files are from the Sveltestrap project? If it's just the 2 in the IFRAME than that's still over 300K compared to 45K in Bootstrap right? I'm just trying to get a comparative feel.

**Comment by nkev** [comment]
Thanks for the Sapper tip BTW. I'm using Go in the back-end though so I'm really only evaluating Svelte and whether I can really drop jQuery and go with Sveltestrap (but only if it's leaner).

**Comment by gthomas-appfolio** [comment]
@nkev it's really hard to separate them as storybook bundles everything together, and the svelte part is just via a plugin.  You should not be looking at Sveltestrap storybook to determine Svelte bundle sizes - it's a React, not a Svelte app.

**Comment by nkev** [comment]
Thanks @gthomas-appfolio, I understand that. I thought maybe only the 432K JS file would be the storybook bundle and one of the other two JS files (inside  the iframe) could be sveltestrap, but without looking into the JS files I could be wrong, of course. Are there any other known sveltestrap public sites that I could check out?

**Comment by cayter** [comment]
@nkev Since you're from golang realm, I'd suggest you to quickly set this up to get a feeling of how SvelteJS bundle size looks like in a real-world application. Here's quick start you can get to experience: https://appist.gitbook.io/appy/getting-started.

**Comment by cayter** [comment]
@nkev Since you're from golang realm, I'd suggest you to quickly set this up to get a feeling of how SvelteJS bundle size looks like in a real-world application. Here's quick start you can get to experience: https://appist.gitbook.io/appy/getting-started.

Disclaimer: I built this web framework by putting together few of the best packages from golang community and made SvelteJS as the primary choice for building the PWA with it. This is how the development with go + webpack-dev-server looks like. https://asciinema.org/a/312186
