### ISSUE TITLE
Styles Overwritten

### ISSUE THREAD

**Issue by anthonycollini** [bestguy/sveltestrap#77]
I have an issue with styles being overwritten and would like some information on how to fix it.

In a component, I import the `Card`, and related, components from sveltestrap.

When I add `CardTitle` to my markup, I see that sveltestrap adds it as a div, rather than the h5 in the bootstrap docs that allows for the proper styling.

To change the styling for all CardTitles in my app, I add a `.card-title` declaration to `global.css`. This changes the card title after save. However, if I resave the component file, or a refresh, the styles get lost, and the card title goes back to incorrect styling.

What do I need to do to overwrite these styles, or change the element type?

**Comment by anthonycollini** [comment]
This was some kind of issue with the compiler caching global.css. Did a hard refresh and it seemed to fix the issue.

**Comment by bestguy** [comment]
We could use h5 as tag, was probably an oversight

**Comment by bestguy** [comment]
https://github.com/bestguy/sveltestrap/issues/78
