### ISSUE TITLE
Use h5 etc for CardTitle

### ISSUE THREAD

**Issue by bestguy** [bestguy/sveltestrap#78]
Currently using a div

**Comment by daytonlowell** [comment]
What about leaving it as a div but applying the BS4 `h5` class to the div by default? Probably have to write some logic so that we don't apply that default class if they pass in `h1` -> `h6` classes.

Source: https://getbootstrap.com/docs/4.4/content/typography/#headings

**Comment by bestguy** [comment]
Thanks, we could, however the `.card-title` class is what defines the look, so `.h5` for styling isn't really needed.  The h* tag is mostly for semantics here.

**Comment by daytonlowell** [comment]
That's fair, though if we're going this route we'll probably need to expose some way for them to use any of the `h*` tags? Probably don't want to force them into `h5`?

**Comment by bestguy** [comment]
Hmm, true.  I was going by the examples here which all use h5: https://getbootstrap.com/docs/4.4/components/card/#titles-text-and-links

but they also mention h* .   
Reactstrap uses div but React allows for the tag to be dynamic: https://github.com/reactstrap/reactstrap/blob/master/src/CardTitle.js#L13

Maybe div is okay?  Haha not sure tbh.

**Comment by bestguy** [comment]
Fixed in v5
