### ISSUE TITLE
Useless "toggle" attribute in Modal code

### ISSUE THREAD

**Issue by frederikhors** [bestguy/sveltestrap#80]
Using Modal I noticed a strange thing also in the Storybook one:

![image](https://user-images.githubusercontent.com/41120635/70658411-39c5f680-1c5e-11ea-9cb6-10ed48f14412.png)

Do you see the `toggle="()=>$$invalidate("open",open=!open)"` string in div?

I think it comes from `<div {...props}` in `Modal.svelte`.

Do we really need it?

**Comment by bestguy** [comment]
Thanks for the heads-up, let me take a look.

**Comment by satb** [comment]
First of all, thank you so much for putting this together. I am still trying to see if I can use it. 

For some reason, even though I try to close the modal, it won't close. So, the html shows this, but modal is still open. 

![image](https://user-images.githubusercontent.com/2095367/71316111-9b851e00-241f-11ea-8401-613f3d3b62e6.png)

**Comment by bestguy** [comment]
Hi @satb did you follow the example in the documentation?
 https://bestguy.github.io/sveltestrap/?path=/story/components--modals

It seems to work fine there

**Comment by satb** [comment]
@bestguy - Seemed like some caching issue with the css in the browser. Started working without changing anything. Thank you so much.

**Comment by frederikhors** [comment]
@satb the issue here is different.

**Comment by bestguy** [comment]
This looks to be correct in more recent builds, thanks for the heads-up Frederik.  Please reopen if you still see issue.
